/*
blurs.pde:

int currentThemeIndex;
int rows;
int columns;
int shapesAmount;
float minS;
float blurAmount;
String[] themes;
PGraphics buffer;
PGraphics blurMask;
ArrayList<PVector> shapes;
void setup() {
  currentThemeIndex = 0;
  rows = 5;
  columns = 8;
  shapesAmount = 100;
  minS = 40;
  blurAmount = 25;
  themes = new String[] {"cyberpunk", "light", "dark", "greyscale", "default", "sunset", "forest", "ice"};
  buffer = createGraphics(width, height);
  blurMask = createGraphics(width, height);
  shapes = new ArrayList<PVector>();
  randomSeed(1);
  fullScreen();
  noLoop();
  for (int i = 0; i < shapesAmount; i++) {
    shapes.add(new PVector(random(width), random(height), random(minS, minS * 10)));
  }
}
void draw() {
  while (currentThemeIndex <= themes.length - 1) {
    themeBlurs(currentThemeIndex);
    currentThemeIndex++;
  }
  exit();
}
void drawGradient(int themeIndex) {
  color[] colours;
  switch(themeIndex) {
    case 0:
      colours = new color[] {color(0, 0, 10), color(100, 0, 130)}; 
      break;
    case 1:
      colours = new color[] {color(220, 230, 240), color(240, 240, 245)}; 
      break;
    case 2:
      colours = new color[] {color(0), color(15)}; 
      break;
    case 3:
      colours = new color[] {color(50 / 3), color(40)}; 
      break;
    case 4:
      colours = new color[] {color(10, 15, 25), color(30, 40, 50)}; 
      break;
    case 5:
      colours = new color[] {color(40, 20, 60), color(240, 130, 90)}; 
      break;
    case 6:
      colours = new color[] {color(20, 40, 30), color(80, 110, 90)}; 
      break;
    case 7:
      colours = new color[] {color(180, 200, 220), color(210, 230, 250)}; 
      break;
    default: 
      colours = new color[] {color(0), color(255)}; 
  }
  for (int y = 0; y < height; y++) {
    float inter = map(y, 0, height, 0, 1);
    color c = lerpColor(colours[0], colours[1], inter);
    stroke(c);
    line(0, y, width, y);
  }
}
void drawShapes(int themeIndex, PGraphics target) {
  color[] colours;
  switch(themeIndex) {
    case 0:
      colours = new color[] {color(20, 5, 30), color(0, 255, 255), color(255, 0, 255), color(80, 0, 100), color(255, 50, 0), color(30, 0, 40), color(60, 0, 80), color(90, 0, 120), color(120, 0, 160)};
      break;
    case 1:
      colours = new color[] {color(240, 240, 245), color(40, 40, 50), color(100, 180, 220), color(200, 200, 210), color(220, 120, 130), color(220, 220, 230), color(210, 210, 220), color(200, 200, 210), color(190, 190, 200)};
      break;
    case 2:
      colours = new color[] {color(15), color(255), color(0, 200, 255), color(40), color(255, 40, 40), color(10), color(20), color(30), color(40)};
      break;
    case 3:
      colours = new color[] {color(95), color(225), color(490 / 3), color(190 / 3), color(310 / 3), color(35), color(55), color(75), color(95)};
      break;
    case 4:
      colours = new color[] {color(85, 95, 105), color(215, 225, 235), color(120, 170, 200), color(50, 60, 80), color(150, 70, 90), color(25, 35, 45), color(45, 55, 65), color(65, 75, 85), color(85, 95, 105)};
      break;
    case 5:
      colours = new color[] {color(240, 180, 120), color(255, 240, 180), color(255, 100, 80), color(180, 90, 60), color(200, 60, 40), color(160, 70, 50), color(180, 80, 60), color(200, 90, 70), color(220, 100, 80)};
      break;
    case 6:
      colours = new color[] {color(100, 130, 90), color(230, 240, 210), color(80, 160, 120), color(60, 80, 50), color(160, 70, 60), color(40, 60, 30), color(50, 70, 40), color(60, 80, 50), color(70, 90, 60)};
      break;
    case 7:
      colours = new color[] {color(200, 220, 240), color(30, 50, 80), color(170, 220, 255), color(180, 200, 220), color(100, 150, 200), color(180, 200, 220), color(190, 210, 230), color(200, 220, 240), color(210, 230, 250)};
      break;
    default:
      colours = new color[] {color(0), color(0), color(0), color(0), color(0), color(0), color(0), color(0), color(0)};
  }
  target.noStroke();
  for (PVector s : shapes) {
    target.fill(colours[(int)random(colours.length)]);
    if (random(1) > 0.3) {
      target.ellipse(s.x, s.y, s.z, s.z);
    } else {
      target.ellipse(s.x, s.y, s.z, s.z * random(0.6, 1.4));
    }
  }
}
void saveAllSections(int themeIndex) {
  File imagesDir = new File(new File(sketchPath("")).getParentFile(), "data/images/sections/" + themes[themeIndex]);
  if (!imagesDir.exists()) {
    imagesDir.mkdirs();
  }
  for (int row = 0; row < rows; row++) {
    for (int col = 0; col < columns; col++) {
      int sectionWidth = width / columns;
      int sectionHeight = height / rows;
      PImage section = get(col * sectionWidth, row * sectionHeight, sectionWidth, sectionHeight);
      section.save(imagesDir.getAbsolutePath() + File.separator + themes[themeIndex] + "Section[" + row + "][" + col + "].png");
      delay(100);
    }
  }
}
void themeBlurs(int themeIndex) {
  drawGradient(themeIndex);
  buffer.beginDraw();
  buffer.clear();
  drawShapes(themeIndex, buffer);
  buffer.endDraw();
  buffer.filter(BLUR, blurAmount);
  image(buffer, 0, 0);
  saveAllSections(themeIndex);
}
*/
void setup() {
  time = 0;
  alpha = 0;
  blockSize = displayWidth / 96.0;
  halfBlockSize = blockSize / 2;
  blockRadius = blockSize * 0.15;
  titleSize = blockSize * 12.5;
  titleHeight = blockSize * 27.5;
  headingSize = blockSize * 7.5;
  subtitleSize = blockSize * 3;
  subtitleHeight = blockSize * 43.5;
  centerX = blockSize * 48;
  centerY = blockSize * 27;
  right = blockSize * 95.5;
  bottom = blockSize * 53.5;
  playerX = halfBlockSize;
  playerY = bottom;
  xSpeed = blockSize / 4;
  ySpeed = 0;
  gravity = blockSize / 40;
  jumpStrength = -halfBlockSize;
  animationS = 0.2;
  benchNineLight = createFont(getParentPath(1) + "data/fonts/BenchNine-Light.ttf", 32);
  benchNineRegular = createFont(getParentPath(1) + "data/fonts/BenchNine-Regular.ttf", 32);
  benchNineBold = createFont(getParentPath(1) + "data/fonts/BenchNine-Bold.ttf", 32);
  hcLogo = loadImage(getParentPath(1) + "data/images/hcLogo.png");
  somLogo = loadImage(getParentPath(1) + "data/images/somLogo.png");
  somLogo.resize(930, 589);
  level = "intro";
  targetLevel = level;
  previousTheme = "";
  theme = "default";
  setColours(false);
  startButton = new Button(blockSize * 40.375, blockSize * 25.125, blockSize * 30, blockSize * 14.75, "Play", blockSize * 13.5, false);
  exitButton = new Button(centerX, blockSize * 34.5, blockSize * 45.25, blockSize * 3.5, "Exit", blockSize * 2.25, false);
  levelsButton = new Button(0, 0, blockSize * 63.125, blockSize * 19.5, blockSize * 15, blockSize * 3.5, "Levels", blockSize * 2.25, true);
  achievementsButton = new Button(blockSize * 63.125, blockSize * 23.25, blockSize * 15, blockSize * 3.5, "Achievements", blockSize * 2.25, false);
  tutorialButton = new Button(blockSize * 63.125, centerY, blockSize * 15, blockSize * 3.5, "Tutorial", blockSize * 2.25, false);
  settingsButton = new Button(blockSize * 63.125, blockSize * 30.75, blockSize * 15, blockSize * 3.5, "Settings", blockSize * 2.25, false);
  backButton = new Button(blockSize * 8, blockSize * 2.25, blockSize * 15, blockSize * 3.5, "Back", blockSize * 2.25, false);
  oneButton = new Button(blockSize * 24.75, blockSize * 7.625, blockSize * 7.5, blockSize * 7.5, "1", headingSize, false);
  twoButton = new Button(blockSize * 32.5, blockSize * 7.625, blockSize * 7.5, blockSize * 7.5, "2", headingSize, false);
  threeButton = new Button(blockSize * 40.25, blockSize * 7.625, blockSize * 7.5, blockSize * 7.5, "3", headingSize, false);
  fourButton = new Button(centerX, blockSize * 7.625, blockSize * 7.5, blockSize * 7.5, "4", headingSize, false);
  fiveButton = new Button(blockSize * 55.75, blockSize * 7.625, blockSize * 7.5, blockSize * 7.5, "5", headingSize, false);
  sixButton = new Button(blockSize * 63.5, blockSize * 7.625, blockSize * 7.5, blockSize * 7.5, "6", headingSize, false);
  sevenButton = new Button(blockSize * 71.25, blockSize * 7.625, blockSize * 7.5, blockSize * 7.5, "7", headingSize, false);
  eightButton = new Button(blockSize * 24.75, blockSize * 15.375, blockSize * 7.5, blockSize * 7.5, "8", headingSize, false);
  nineButton = new Button(blockSize * 32.5, blockSize * 15.375, blockSize * 7.5, blockSize * 7.5, "9", headingSize, false);
  tenButton = new Button(blockSize * 40.25, blockSize * 15.375, blockSize * 7.5, blockSize * 7.5, "10", headingSize, false);
  elevenButton = new Button(centerX, blockSize * 15.375, blockSize * 7.5, blockSize * 7.5, "11", headingSize, false);
  twelveButton = new Button(blockSize * 55.75, blockSize * 15.375, blockSize * 7.5, blockSize * 7.5, "12", headingSize, false);
  thirteenButton = new Button(blockSize * 63.5, blockSize * 15.375, blockSize * 7.5, blockSize * 7.5, "13", headingSize, false);
  fourteenButton = new Button(blockSize * 71.25, blockSize * 15.375, blockSize * 7.5, blockSize * 7.5, "14", headingSize, false);
  fifteenButton = new Button(blockSize * 24.75, blockSize * 23.125, blockSize * 7.5, blockSize * 7.5, "15", headingSize, false);
  sixteenButton = new Button(blockSize * 32.5, blockSize * 23.125, blockSize * 7.5, blockSize * 7.5, "16", headingSize, false);
  seventeenButton = new Button(blockSize * 40.25, blockSize * 23.125, blockSize * 7.5, blockSize * 7.5, "17", headingSize, false);
  eighteenButton = new Button(centerX, blockSize * 23.125, blockSize * 7.5, blockSize * 7.5, "18", headingSize, false);
  nineteenButton = new Button(blockSize * 55.75, blockSize * 23.125, blockSize * 7.5, blockSize * 7.5, "19", headingSize, false);
  twentyButton = new Button(blockSize * 63.5, blockSize * 23.125, blockSize * 7.5, blockSize * 7.5, "20", headingSize, false);
  twentyoneButton = new Button(blockSize * 71.25, blockSize * 23.125, blockSize * 7.5, blockSize * 7.5, "21", headingSize, false);
  twentytwoButton = new Button(blockSize * 24.75, blockSize * 30.875, blockSize * 7.5, blockSize * 7.5, "22", headingSize, false);
  twentythreeButton = new Button(blockSize * 32.5, blockSize * 30.875, blockSize * 7.5, blockSize * 7.5, "23", headingSize, false);
  twentyfourButton = new Button(blockSize * 40.25, blockSize * 30.875, blockSize * 7.5, blockSize * 7.5, "24", headingSize, false);
  twentyfiveButton = new Button(centerX, blockSize * 30.875, blockSize * 7.5, blockSize * 7.5, "25", headingSize, false);
  twentysixButton = new Button(blockSize * 55.75, blockSize * 30.875, blockSize * 7.5, blockSize * 7.5, "26", headingSize, false);
  twentysevenButton = new Button(blockSize * 63.5, blockSize * 30.875, blockSize * 7.5, blockSize * 7.5, "27", headingSize, false);
  twentyeightButton = new Button(blockSize * 71.25, blockSize * 30.875, blockSize * 7.5, blockSize * 7.5, "28", headingSize, false);
  twentynineButton = new Button(blockSize * 24.75, blockSize * 38.625, blockSize * 7.5, blockSize * 7.5, "29", headingSize, false);
  thirtyButton = new Button(blockSize * 32.5, blockSize * 38.625, blockSize * 7.5, blockSize * 7.5, "30", headingSize, false);
  thirtyoneButton = new Button(blockSize * 40.25, blockSize * 38.625, blockSize * 7.5, blockSize * 7.5, "31", headingSize, false);
  thirtytwoButton = new Button(centerX, blockSize * 38.625, blockSize * 7.5, blockSize * 7.5, "32", headingSize, false);
  thirtythreeButton = new Button(blockSize * 55.75, blockSize * 38.625, blockSize * 7.5, blockSize * 7.5, "33", headingSize, false);
  thirtyfourButton = new Button(blockSize * 63.5, blockSize * 38.625, blockSize * 7.5, blockSize * 7.5, "34", headingSize, false);
  thirtyfiveButton = new Button(blockSize * 71.25, blockSize * 38.625, blockSize * 7.5, blockSize * 7.5, "35", headingSize, false);
  thirtysixButton = new Button(blockSize * 24.75, blockSize * 46.375, blockSize * 7.5, blockSize * 7.5, "36", headingSize, false);
  thirtysevenButton = new Button(blockSize * 32.5, blockSize * 46.375, blockSize * 7.5, blockSize * 7.5, "37", headingSize, false);
  thirtyeightButton = new Button(blockSize * 40.25, blockSize * 46.375, blockSize * 7.5, blockSize * 7.5, "38", headingSize, false);
  thirtynineButton = new Button(centerX, blockSize * 46.375, blockSize * 7.5, blockSize * 7.5, "39", headingSize, false);
  fortyButton = new Button(blockSize * 55.75, blockSize * 46.375, blockSize * 7.5, blockSize * 7.5, "40", headingSize, false);
  fortyoneButton = new Button(blockSize * 63.5, blockSize * 46.375, blockSize * 7.5, blockSize * 7.5, "41", headingSize, false);
  fortytwoButton = new Button(blockSize * 71.25, blockSize * 46.375, blockSize * 7.5, blockSize * 7.5, "42", headingSize, false);
  themeButton = new Button(centerX, blockSize * 21.375, blockSize * 15, blockSize * 3.5, "Theme", blockSize * 2.25, false);
  graphicsButton = new Button(centerX, blockSize * 25.125, blockSize * 15, blockSize * 3.5, "Graphics", blockSize * 2.25, false);
  audioButton = new Button(centerX, blockSize * 28.875, blockSize * 15, blockSize * 3.5, "Audio", blockSize * 2.25, false);
  aboutButton = new Button(centerX, blockSize * 32.625, blockSize * 15, blockSize * 3.5, "About", blockSize * 2.25, false);
  cyberpunkButton = new Button(centerX, blockSize * 13.875, blockSize * 15, blockSize * 3.5, "Cyberpunk", blockSize * 2.25, false);
  lightButton = new Button(centerX, blockSize * 17.625, blockSize * 15, blockSize * 3.5, "Light", blockSize * 2.25, false);
  darkButton = new Button(centerX, blockSize * 21.375, blockSize * 15, blockSize * 3.5, "Dark", blockSize * 2.25, false);
  greyscaleButton = new Button(centerX, blockSize * 25.125, blockSize * 15, blockSize * 3.5, "Greyscale", blockSize * 2.25, false);
  defaultButton = new Button(centerX, blockSize * 28.875, blockSize * 15, blockSize * 3.5, "Default", blockSize * 2.25, false);
  sunsetButton = new Button(centerX, blockSize * 32.625, blockSize * 15, blockSize * 3.5, "Sunset", blockSize * 2.25, false);
  forestButton = new Button(centerX, blockSize * 36.375, blockSize * 15, blockSize * 3.5, "Forest", blockSize * 2.25, false);
  iceButton = new Button(centerX, blockSize * 40.125, blockSize * 15, blockSize * 3.5, "Ice", blockSize * 2.25, false);
  cursor = new Cursor();
  player = new Player();
  tutorial1Shown = false;
  tutorial2Shown = false;
  tutorial3Shown = false;
  tutorial4Shown = false;
  tutorial5Shown = false;
  about1Shown = false;
  about2Shown = false;
  about3Shown = false;
  about4Shown = false;
  about5Shown = false;
  about6Shown = false;
  levelNameShown = false;
  onGround = false;
  movingLeft = false;
  movingRight = false;
  fadeComplete = false;
  themes = new String[] {"cyberpunk", "light", "dark", "greyscale", "default", "sunset", "forest", "ice"};
  platformExample = new Platform(centerX, blockSize * 30.75, blockSize * 5, blockSize);
  level3Platform1 = new Platform(blockSize * 93.5, blockSize * 50.5, blockSize * 5, blockSize);
  level4Platform1 = new Platform(blockSize * 88.5, blockSize * 50.5, blockSize * 5, blockSize);
  level4Platform2 = new Platform(blockSize * 93.5, blockSize * 47, blockSize * 5, blockSize);
  level5Platform1 = new Platform(blockSize * 33.5, blockSize * 50.5, blockSize * 5, blockSize);
  level5Platform2 = new Platform(blockSize * 38.5, blockSize * 47, blockSize * 5, blockSize);
  level5Platform3 = new Platform(blockSize * 43.5, blockSize * 43.5, blockSize * 5, blockSize);
  level5Platform4 = new Platform(blockSize * 48.5, blockSize * 40, blockSize * 5, blockSize);
  level5Platform5 = new Platform(blockSize * 53.5, blockSize * 36.5, blockSize * 5, blockSize);
  level5Platform6 = new Platform(blockSize * 58.5, blockSize * 33, blockSize * 5, blockSize);
  level5Platform7 = new Platform(blockSize * 63.5, blockSize * 29.5, blockSize * 5, blockSize);
  level5Platform8 = new Platform(blockSize * 68.5, blockSize * 26, blockSize * 5, blockSize);
  level5Platform9 = new Platform(blockSize * 73.5, blockSize * 22.5, blockSize * 5, blockSize);
  level5Platform10 = new Platform(blockSize * 78.5, blockSize * 19, blockSize * 5, blockSize);
  level5Platform11 = new Platform(blockSize * 83.5, blockSize * 15.5, blockSize * 5, blockSize);
  level5Platform12 = new Platform(blockSize * 88.5, blockSize * 12, blockSize * 5, blockSize);
  level5Platform13 = new Platform(blockSize * 93.5, blockSize * 8.5, blockSize * 5, blockSize);
  level6Platform1 = new Platform(blockSize * 84.5, blockSize * 50.5, blockSize * 5, blockSize);
  level7Platform1 = new Platform(blockSize * 79.5, blockSize * 50.5, blockSize * 5, blockSize);
  level7Platform2 = new Platform(blockSize * 84.5, blockSize * 47, blockSize * 5, blockSize);
  level8Platform1 = new Platform(blockSize * 24.5, blockSize * 50.5, blockSize * 5, blockSize);
  level8Platform2 = new Platform(blockSize * 29.5, blockSize * 47, blockSize * 5, blockSize);
  level8Platform3 = new Platform(blockSize * 34.5, blockSize * 43.5, blockSize * 5, blockSize);
  level8Platform4 = new Platform(blockSize * 39.5, blockSize * 40, blockSize * 5, blockSize);
  level8Platform5 = new Platform(blockSize * 44.5, blockSize * 36.5, blockSize * 5, blockSize);
  level8Platform6 = new Platform(blockSize * 49.5, blockSize * 33, blockSize * 5, blockSize);
  level8Platform7 = new Platform(blockSize * 54.5, blockSize * 29.5, blockSize * 5, blockSize);
  level8Platform8 = new Platform(blockSize * 59.5, blockSize * 26, blockSize * 5, blockSize);
  level8Platform9 = new Platform(blockSize * 64.5, blockSize * 22.5, blockSize * 5, blockSize);
  level8Platform10 = new Platform(blockSize * 69.5, blockSize * 19, blockSize * 5, blockSize);
  level8Platform11 = new Platform(blockSize * 74.5, blockSize * 15.5, blockSize * 5, blockSize);
  level8Platform12 = new Platform(blockSize * 79.5, blockSize * 12, blockSize * 5, blockSize);
  level8Platform13 = new Platform(blockSize * 84.5, blockSize * 8.5, blockSize * 5, blockSize);
  level9Platform1 = new Platform(blockSize * 45, blockSize * 50.5, blockSize * 90, blockSize);
  level10Platform1 = new Platform(blockSize * 45, blockSize * 50.5, blockSize * 90, blockSize);
  level10Platform2 = new Platform(blockSize * 51, blockSize * 47, blockSize * 90, blockSize);
  level11Platform1 = new Platform(blockSize * 45, blockSize * 50.5, blockSize * 90, blockSize);
  level11Platform2 = new Platform(blockSize * 51, blockSize * 47, blockSize * 90, blockSize);
  level11Platform3 = new Platform(blockSize * 45, blockSize * 43.5, blockSize * 90, blockSize);
  level11Platform4 = new Platform(blockSize * 51, blockSize * 40, blockSize * 90, blockSize);
  level11Platform5 = new Platform(blockSize * 45, blockSize * 36.5, blockSize * 90, blockSize);
  level11Platform6 = new Platform(blockSize * 51, blockSize * 33, blockSize * 90, blockSize);
  level11Platform7 = new Platform(blockSize * 45, blockSize * 29.5, blockSize * 90, blockSize);
  level11Platform8 = new Platform(blockSize * 51, blockSize * 26, blockSize * 90, blockSize);
  level11Platform9 = new Platform(blockSize * 45, blockSize * 22.5, blockSize * 90, blockSize);
  level11Platform10 = new Platform(blockSize * 51, blockSize * 19, blockSize * 90, blockSize);
  level11Platform11 = new Platform(blockSize * 45, blockSize * 15.5, blockSize * 90, blockSize);
  level11Platform12 = new Platform(blockSize * 51, blockSize * 12, blockSize * 90, blockSize);
  level11Platform13 = new Platform(blockSize * 45, blockSize * 8.5, blockSize * 90, blockSize);
  level12Platform1 = new Platform(right, blockSize * 50.5, blockSize, blockSize);
  level13Platform1 = new Platform(blockSize * 90.5, blockSize * 50.5, blockSize, blockSize);
  level13Platform2 = new Platform(right, blockSize * 47, blockSize, blockSize);
  level14Platform1 = new Platform(blockSize * 35.5, blockSize * 50.5, blockSize, blockSize);
  level14Platform2 = new Platform(blockSize * 40.5, blockSize * 47, blockSize, blockSize);
  level14Platform3 = new Platform(blockSize * 45.5, blockSize * 43.5, blockSize, blockSize);
  level14Platform4 = new Platform(blockSize * 50.5, blockSize * 40, blockSize, blockSize);
  level14Platform5 = new Platform(blockSize * 55.5, blockSize * 36.5, blockSize, blockSize);
  level14Platform6 = new Platform(blockSize * 60.5, blockSize * 33, blockSize, blockSize);
  level14Platform7 = new Platform(blockSize * 65.5, blockSize * 29.5, blockSize, blockSize);
  level14Platform8 = new Platform(blockSize * 70.5, blockSize * 26, blockSize, blockSize);
  level14Platform9 = new Platform(blockSize * 75.5, blockSize * 22.5, blockSize, blockSize);
  level14Platform10 = new Platform(blockSize * 80.5, blockSize * 19, blockSize, blockSize);
  level14Platform11 = new Platform(blockSize * 85.5, blockSize * 15.5, blockSize, blockSize);
  level14Platform12 = new Platform(blockSize * 90.5, blockSize * 12, blockSize, blockSize);
  level14Platform13 = new Platform(right, blockSize * 8.5, blockSize, blockSize);
  level15Platform1 = new Platform(blockSize * 86.5, blockSize * 50.5, blockSize, blockSize);
  level16Platform1 = new Platform(blockSize * 81.5, blockSize * 50.5, blockSize, blockSize);
  level16Platform2 = new Platform(blockSize * 86.5, blockSize * 47, blockSize, blockSize);
  level17Platform1 = new Platform(blockSize * 26.5, blockSize * 50.5, blockSize, blockSize);
  level17Platform2 = new Platform(blockSize * 31.5, blockSize * 47, blockSize, blockSize);
  level17Platform3 = new Platform(blockSize * 36.5, blockSize * 43.5, blockSize, blockSize);
  level17Platform4 = new Platform(blockSize * 41.5, blockSize * 40, blockSize, blockSize);
  level17Platform5 = new Platform(blockSize * 46.5, blockSize * 36.5, blockSize, blockSize);
  level17Platform6 = new Platform(blockSize * 51.5, blockSize * 33, blockSize, blockSize);
  level17Platform7 = new Platform(blockSize * 56.5, blockSize * 29.5, blockSize, blockSize);
  level17Platform8 = new Platform(blockSize * 61.5, blockSize * 26, blockSize, blockSize);
  level17Platform9 = new Platform(blockSize * 66.5, blockSize * 22.5, blockSize, blockSize);
  level17Platform10 = new Platform(blockSize * 71.5, blockSize * 19, blockSize, blockSize);
  level17Platform11 = new Platform(blockSize * 76.5, blockSize * 15.5, blockSize, blockSize);
  level17Platform12 = new Platform(blockSize * 81.5, blockSize * 12, blockSize, blockSize);
  level17Platform13 = new Platform(blockSize * 86.5, blockSize * 8.5, blockSize, blockSize);
  level18Platform1 = new Platform(centerX, blockSize * 50.5, blockSize * 5, blockSize);
  level18Platform2 = new Platform(centerX, blockSize * 47, blockSize * 5, blockSize);
  level19Platform1 = new Platform(centerX, blockSize * 50.5, blockSize * 5, blockSize);
  level19Platform2 = new Platform(centerX, blockSize * 47, blockSize * 5, blockSize);
  level19Platform3 = new Platform(centerX, blockSize * 43.5, blockSize * 5, blockSize);
  level19Platform4 = new Platform(centerX, blockSize * 40, blockSize * 5, blockSize);
  level19Platform5 = new Platform(centerX, blockSize * 36.5, blockSize * 5, blockSize);
  level19Platform6 = new Platform(centerX, blockSize * 33, blockSize * 5, blockSize);
  level19Platform7 = new Platform(centerX, blockSize * 29.5, blockSize * 5, blockSize);
  level19Platform8 = new Platform(centerX, blockSize * 26, blockSize * 5, blockSize);
  level19Platform9 = new Platform(centerX, blockSize * 22.5, blockSize * 5, blockSize);
  level19Platform10 = new Platform(centerX, blockSize * 19, blockSize * 5, blockSize);
  level19Platform11 = new Platform(centerX, blockSize * 15.5, blockSize * 5, blockSize);
  level19Platform12 = new Platform(centerX, blockSize * 12, blockSize * 5, blockSize);
  level19Platform13 = new Platform(centerX, blockSize * 8.5, blockSize * 5, blockSize);
  level20Platform1 = new Platform(centerX, blockSize * 50.5, blockSize * 5, blockSize);
  level20Platform2 = new Platform(centerX, blockSize * 47, blockSize * 5, blockSize);
  level21Platform1 = new Platform(centerX, blockSize * 50.5, blockSize * 5, blockSize);
  level21Platform2 = new Platform(centerX, blockSize * 47, blockSize * 5, blockSize);
  level21Platform3 = new Platform(centerX, blockSize * 43.5, blockSize * 5, blockSize);
  level21Platform4 = new Platform(centerX, blockSize * 40, blockSize * 5, blockSize);
  level21Platform5 = new Platform(centerX, blockSize * 36.5, blockSize * 5, blockSize);
  level21Platform6 = new Platform(centerX, blockSize * 33, blockSize * 5, blockSize);
  level21Platform7 = new Platform(centerX, blockSize * 29.5, blockSize * 5, blockSize);
  level21Platform8 = new Platform(centerX, blockSize * 26, blockSize * 5, blockSize);
  level21Platform9 = new Platform(centerX, blockSize * 22.5, blockSize * 5, blockSize);
  level21Platform10 = new Platform(centerX, blockSize * 19, blockSize * 5, blockSize);
  level21Platform11 = new Platform(centerX, blockSize * 15.5, blockSize * 5, blockSize);
  level21Platform12 = new Platform(centerX, blockSize * 12, blockSize * 5, blockSize);
  level21Platform13 = new Platform(centerX, blockSize * 8.5, blockSize * 5, blockSize);
  level22Platform1 = new Platform(centerX, blockSize * 50.5, blockSize, blockSize);
  level22Platform2 = new Platform(centerX, blockSize * 47, blockSize, blockSize);
  level23Platform1 = new Platform(centerX, blockSize * 50.5, blockSize, blockSize);
  level23Platform2 = new Platform(centerX, blockSize * 47, blockSize, blockSize);
  level23Platform3 = new Platform(centerX, blockSize * 43.5, blockSize, blockSize);
  level23Platform4 = new Platform(centerX, blockSize * 40, blockSize, blockSize);
  level23Platform5 = new Platform(centerX, blockSize * 36.5, blockSize, blockSize);
  level23Platform6 = new Platform(centerX, blockSize * 33, blockSize, blockSize);
  level23Platform7 = new Platform(centerX, blockSize * 29.5, blockSize, blockSize);
  level23Platform8 = new Platform(centerX, blockSize * 26, blockSize, blockSize);
  level23Platform9 = new Platform(centerX, blockSize * 22.5, blockSize, blockSize);
  level23Platform10 = new Platform(centerX, blockSize * 19, blockSize, blockSize);
  level23Platform11 = new Platform(centerX, blockSize * 15.5, blockSize, blockSize);
  level23Platform12 = new Platform(centerX, blockSize * 12, blockSize, blockSize);
  level23Platform13 = new Platform(centerX, blockSize * 8.5, blockSize, blockSize);
  level24Platform1 = new Platform(centerX, blockSize * 50.5, blockSize, blockSize);
  level24Platform2 = new Platform(centerX, blockSize * 47, blockSize, blockSize);
  level25Platform1 = new Platform(centerX, blockSize * 50.5, blockSize, blockSize);
  level25Platform2 = new Platform(centerX, blockSize * 47, blockSize, blockSize);
  level25Platform3 = new Platform(centerX, blockSize * 43.5, blockSize, blockSize);
  level25Platform4 = new Platform(centerX, blockSize * 40, blockSize, blockSize);
  level25Platform5 = new Platform(centerX, blockSize * 36.5, blockSize, blockSize);
  level25Platform6 = new Platform(centerX, blockSize * 33, blockSize, blockSize);
  level25Platform7 = new Platform(centerX, blockSize * 29.5, blockSize, blockSize);
  level25Platform8 = new Platform(centerX, blockSize * 26, blockSize, blockSize);
  level25Platform9 = new Platform(centerX, blockSize * 22.5, blockSize, blockSize);
  level25Platform10 = new Platform(centerX, blockSize * 19, blockSize, blockSize);
  level25Platform11 = new Platform(centerX, blockSize * 15.5, blockSize, blockSize);
  level25Platform12 = new Platform(centerX, blockSize * 12, blockSize, blockSize);
  level25Platform13 = new Platform(centerX, blockSize * 8.5, blockSize, blockSize);
  level30Platform1 = new Platform(blockSize * 88.5, blockSize * 50.5, blockSize * 5, blockSize);
  level30Platform2 = new Platform(blockSize * 93.5, blockSize * 47, blockSize * 5, blockSize);
  level31Platform1 = new Platform(blockSize * 33.5, blockSize * 50.5, blockSize * 5, blockSize);
  level31Platform2 = new Platform(blockSize * 38.5, blockSize * 47, blockSize * 5, blockSize);
  level31Platform3 = new Platform(blockSize * 43.5, blockSize * 43.5, blockSize * 5, blockSize);
  level31Platform4 = new Platform(blockSize * 48.5, blockSize * 40, blockSize * 5, blockSize);
  level31Platform5 = new Platform(bottom, blockSize * 36.5, blockSize * 5, blockSize);
  level31Platform6 = new Platform(blockSize * 58.5, blockSize * 33, blockSize * 5, blockSize);
  level31Platform7 = new Platform(blockSize * 63.5, blockSize * 29.5, blockSize * 5, blockSize);
  level31Platform8 = new Platform(blockSize * 68.5, blockSize * 26, blockSize * 5, blockSize);
  level31Platform9 = new Platform(blockSize * 73.5, blockSize * 22.5, blockSize * 5, blockSize);
  level31Platform10 = new Platform(blockSize * 78.5, blockSize * 19, blockSize * 5, blockSize);
  level31Platform11 = new Platform(blockSize * 83.5, blockSize * 15.5, blockSize * 5, blockSize);
  level31Platform12 = new Platform(blockSize * 88.5, blockSize * 12, blockSize * 5, blockSize);
  level31Platform13 = new Platform(blockSize * 93.5, blockSize * 8.5, blockSize * 5, blockSize);
  level32Platform1 = new Platform(blockSize * 84.5, blockSize * 50.5, blockSize * 5, blockSize);
  level33Platform1 = new Platform(blockSize * 79.5, blockSize * 50.5, blockSize * 5, blockSize);
  level33Platform2 = new Platform(blockSize * 84.5, blockSize * 47, blockSize * 5, blockSize);
  level34Platform1 = new Platform(blockSize * 24.5, blockSize * 50.5, blockSize * 5, blockSize);
  level34Platform2 = new Platform(blockSize * 29.5, blockSize * 47, blockSize * 5, blockSize);
  level34Platform3 = new Platform(blockSize * 34.5, blockSize * 43.5, blockSize * 5, blockSize);
  level34Platform4 = new Platform(blockSize * 39.5, blockSize * 40, blockSize * 5, blockSize);
  level34Platform5 = new Platform(blockSize * 44.5, blockSize * 36.5, blockSize * 5, blockSize);
  level34Platform6 = new Platform(blockSize * 49.5, blockSize * 33, blockSize * 5, blockSize);
  level34Platform7 = new Platform(blockSize * 54.5, blockSize * 29.5, blockSize * 5, blockSize);
  level34Platform8 = new Platform(blockSize * 59.5, blockSize * 26, blockSize * 5, blockSize);
  level34Platform9 = new Platform(blockSize * 64.5, blockSize * 22.5, blockSize * 5, blockSize);
  level34Platform10 = new Platform(blockSize * 69.5, blockSize * 19, blockSize * 5, blockSize);
  level34Platform11 = new Platform(blockSize * 74.5, blockSize * 15.5, blockSize * 5, blockSize);
  level34Platform12 = new Platform(blockSize * 79.5, blockSize * 12, blockSize * 5, blockSize);
  level34Platform13 = new Platform(blockSize * 84.5, blockSize * 8.5, blockSize * 5, blockSize);
  level35Platform1 = new Platform(blockSize * 90.5, blockSize * 50.5, blockSize, blockSize);
  level35Platform2 = new Platform(right, blockSize * 47, blockSize, blockSize);
  level36Platform1 = new Platform(blockSize * 35.5, blockSize * 50.5, blockSize, blockSize);
  level36Platform2 = new Platform(blockSize * 40.5, blockSize * 47, blockSize, blockSize);
  level36Platform3 = new Platform(blockSize * 45.5, blockSize * 43.5, blockSize, blockSize);
  level36Platform4 = new Platform(blockSize * 50.5, blockSize * 40, blockSize, blockSize);
  level36Platform5 = new Platform(blockSize * 55.5, blockSize * 36.5, blockSize, blockSize);
  level36Platform6 = new Platform(blockSize * 60.5, blockSize * 33, blockSize, blockSize);
  level36Platform7 = new Platform(blockSize * 65.5, blockSize * 29.5, blockSize, blockSize);
  level36Platform8 = new Platform(blockSize * 70.5, blockSize * 26, blockSize, blockSize);
  level36Platform9 = new Platform(blockSize * 75.5, blockSize * 22.5, blockSize, blockSize);
  level36Platform10 = new Platform(blockSize * 80.5, blockSize * 19, blockSize, blockSize);
  level36Platform11 = new Platform(blockSize * 85.5, blockSize * 15.5, blockSize, blockSize);
  level36Platform12 = new Platform(blockSize * 90.5, blockSize * 12, blockSize, blockSize);
  level36Platform13 = new Platform(right, blockSize * 8.5, blockSize, blockSize);
  level37Platform1 = new Platform(blockSize * 86.5, blockSize * 50.5, blockSize, blockSize);
  level38Platform1 = new Platform(blockSize * 81.5, blockSize * 50.5, blockSize, blockSize);
  level38Platform2 = new Platform(blockSize * 86.5, blockSize * 47, blockSize, blockSize);
  level39Platform1 = new Platform(blockSize * 26.5, blockSize * 50.5, blockSize, blockSize);
  level39Platform2 = new Platform(blockSize * 31.5, blockSize * 47, blockSize, blockSize);
  level39Platform3 = new Platform(blockSize * 36.5, blockSize * 43.5, blockSize, blockSize);
  level39Platform4 = new Platform(blockSize * 41.5, blockSize * 40, blockSize, blockSize);
  level39Platform5 = new Platform(blockSize * 46.5, blockSize * 36.5, blockSize, blockSize);
  level39Platform6 = new Platform(blockSize * 51.5, blockSize * 33, blockSize, blockSize);
  level39Platform7 = new Platform(blockSize * 56.5, blockSize * 29.5, blockSize, blockSize);
  level39Platform8 = new Platform(blockSize * 61.5, blockSize * 26, blockSize, blockSize);
  level39Platform9 = new Platform(blockSize * 66.5, blockSize * 22.5, blockSize, blockSize);
  level39Platform10 = new Platform(blockSize * 71.5, blockSize * 19, blockSize, blockSize);
  level39Platform11 = new Platform(blockSize * 76.5, blockSize * 15.5, blockSize, blockSize);
  level39Platform12 = new Platform(blockSize * 81.5, blockSize * 12, blockSize, blockSize);
  level39Platform13 = new Platform(blockSize * 86.5, blockSize * 8.5, blockSize, blockSize);
  level40Platform1 = new Platform(blockSize * 45, blockSize * 50.25, blockSize * 90, halfBlockSize);
  level41Platform1 = new Platform(blockSize * 45, blockSize * 50.25, blockSize * 90, halfBlockSize);
  level41Platform2 = new Platform(blockSize * 51, blockSize * 46.75, blockSize * 90, halfBlockSize);
  level42Platform1 = new Platform(blockSize * 45, blockSize * 50.25, blockSize * 90, halfBlockSize);
  level42Platform2 = new Platform(blockSize * 51, blockSize * 46.75, blockSize * 90, halfBlockSize);
  level42Platform3 = new Platform(blockSize * 45, blockSize * 43.25, blockSize * 90, halfBlockSize);
  level42Platform4 = new Platform(blockSize * 51, blockSize * 39.75, blockSize * 90, halfBlockSize);
  level42Platform5 = new Platform(blockSize * 45, blockSize * 36.25, blockSize * 90, halfBlockSize);
  level42Platform6 = new Platform(blockSize * 51, blockSize * 32.75, blockSize * 90, halfBlockSize);
  level42Platform7 = new Platform(blockSize * 45, blockSize * 29.25, blockSize * 90, halfBlockSize);
  level42Platform8 = new Platform(blockSize * 51, blockSize * 25.75, blockSize * 90, halfBlockSize);
  level42Platform9 = new Platform(blockSize * 45, blockSize * 22.25, blockSize * 90, halfBlockSize);
  level42Platform10 = new Platform(blockSize * 51, blockSize * 18.75, blockSize * 90, halfBlockSize);
  level42Platform11 = new Platform(blockSize * 45, blockSize * 15.25, blockSize * 90, halfBlockSize);
  level42Platform12 = new Platform(blockSize * 51, blockSize * 11.75, blockSize * 90, halfBlockSize);
  level42Platform13 = new Platform(blockSize * 45, blockSize * 8.25, blockSize * 90, halfBlockSize);
  trailCheckbox = new Checkbox(centerX, blockSize * 25.425, blockSize * 2.5, blockSize * 2.5, "checked");
  jumpAnimationCheckbox = new Checkbox(centerX, blockSize * 28.575, blockSize * 2.5, blockSize * 2.5, "default");
  randomClickCheckbox = new Checkbox(centerX, blockSize * 22.275, blockSize * 2.5, blockSize * 2.5, "checked");
  buttonClickCheckbox = new Checkbox(centerX, blockSize * 25.425, blockSize * 2.5, blockSize * 2.5, "checked");
  levelClearCheckbox = new Checkbox(centerX, blockSize * 28.575, blockSize * 2.5, blockSize * 2.5, "checked");
  playerDeathCheckbox = new Checkbox(centerX, blockSize * 31.725, blockSize * 2.5, blockSize * 2.5, "checked");
  mountain1 = new Mountain(displayHeight * 0.7, 0.15, 0.05, mountain1Colour, 800, 1 * getLevel(level));
  mountain2 = new Mountain(displayHeight * 0.7, 0.3, 0.15, mountain2Colour, 600, 2 * getLevel(level));
  mountain3 = new Mountain(displayHeight * 0.7, 0.5, 0.25, mountain3Colour, 400, 3 * getLevel(level));
  mountain4 = new Mountain(displayHeight * 0.7, 0.7, 0.35, mountain4Colour, 200, 4 * getLevel(level));
  levelClear = new SoundFile(this, getParentPath(1) + "data/sounds/levelClear.mp3");
  playerDeath = new SoundFile(this, getParentPath(1) + "data/sounds/playerDeath.mp3");
  randomClick = new SoundFile(this, getParentPath(1) + "data/sounds/randomClick.mp3");
  buttonClick = new SoundFile(this, getParentPath(1) + "data/sounds/buttonClick.mp3");
  achievementPopup = new SoundFile(this, getParentPath(1) + "data/sounds/achievementPopup.mp3");
  sections = new PImage[5][8];
  achievement1 = new Achievement(1, 0, blockSize * 10.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement2 = new Achievement(2, 0, blockSize * 28.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement3 = new Achievement(3, 0, blockSize * 46.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement4 = new Achievement(4, 0, blockSize * 64.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement5 = new Achievement(0, 1, blockSize * 10.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement6 = new Achievement(1, 1, blockSize * 28.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement7 = new Achievement(2, 1, blockSize * 46.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement8 = new Achievement(3, 1, blockSize * 64.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement9 = new Achievement(4, 1, blockSize * 10.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement10 = new Achievement(0, 2, blockSize * 28.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement11 = new Achievement(1, 2, blockSize * 46.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  achievement12 = new Achievement(2, 2, blockSize * 64.7, blockSize * 7.225, "Interesting Title", "A very interesting subtitle", true);
  deathPlatformExample = new DeathPlatform(centerX, blockSize * 30.75, blockSize * 5, blockSize);
  level26DeathPlatform1 = new DeathPlatform(centerX, bottom, blockSize, blockSize);
  level27DeathPlatform1 = new DeathPlatform(blockSize * 32, bottom, blockSize, blockSize);
  level27DeathPlatform2 = new DeathPlatform(blockSize * 64, bottom, blockSize, blockSize);
  level28DeathPlatform1 = new DeathPlatform(blockSize * 2.7, bottom, blockSize, blockSize);
  level28DeathPlatform2 = new DeathPlatform(blockSize * 5.9, bottom, blockSize, blockSize);
  level28DeathPlatform3 = new DeathPlatform(blockSize * 9.1, bottom, blockSize, blockSize);
  level28DeathPlatform4 = new DeathPlatform(blockSize * 12.3, bottom, blockSize, blockSize);
  level28DeathPlatform5 = new DeathPlatform(blockSize * 15.5, bottom, blockSize, blockSize);
  level28DeathPlatform6 = new DeathPlatform(blockSize * 18.7, bottom, blockSize, blockSize);
  level28DeathPlatform7 = new DeathPlatform(blockSize * 21.9, bottom, blockSize, blockSize);
  level28DeathPlatform8 = new DeathPlatform(blockSize * 25.1, bottom, blockSize, blockSize);
  level28DeathPlatform9 = new DeathPlatform(blockSize * 28.3, bottom, blockSize, blockSize);
  level28DeathPlatform10 = new DeathPlatform(blockSize * 31.5, bottom, blockSize, blockSize);
  level28DeathPlatform11 = new DeathPlatform(blockSize * 34.7, bottom, blockSize, blockSize);
  level28DeathPlatform12 = new DeathPlatform(blockSize * 37.9, bottom, blockSize, blockSize);
  level28DeathPlatform13 = new DeathPlatform(blockSize * 41.1, bottom, blockSize, blockSize);
  level28DeathPlatform14 = new DeathPlatform(blockSize * 44.3, bottom, blockSize, blockSize);
  level28DeathPlatform15 = new DeathPlatform(blockSize * 47.5, bottom, blockSize, blockSize);
  level28DeathPlatform16 = new DeathPlatform(blockSize * 50.7, bottom, blockSize, blockSize);
  level28DeathPlatform17 = new DeathPlatform(blockSize * 53.9, bottom, blockSize, blockSize);
  level28DeathPlatform18 = new DeathPlatform(blockSize * 57.1, bottom, blockSize, blockSize);
  level28DeathPlatform19 = new DeathPlatform(blockSize * 60.3, bottom, blockSize, blockSize);
  level28DeathPlatform20 = new DeathPlatform(blockSize * 63.5, bottom, blockSize, blockSize);
  level28DeathPlatform21 = new DeathPlatform(blockSize * 66.7, bottom, blockSize, blockSize);
  level28DeathPlatform22 = new DeathPlatform(blockSize * 69.9, bottom, blockSize, blockSize);
  level28DeathPlatform23 = new DeathPlatform(blockSize * 73.1, bottom, blockSize, blockSize);
  level28DeathPlatform24 = new DeathPlatform(blockSize * 76.3, bottom, blockSize, blockSize);
  level28DeathPlatform25 = new DeathPlatform(blockSize * 79.5, bottom, blockSize, blockSize);
  level28DeathPlatform26 = new DeathPlatform(blockSize * 82.7, bottom, blockSize, blockSize);
  level28DeathPlatform27 = new DeathPlatform(blockSize * 85.9, bottom, blockSize, blockSize);
  level28DeathPlatform28 = new DeathPlatform(blockSize * 89.1, bottom, blockSize, blockSize);
  level28DeathPlatform29 = new DeathPlatform(blockSize * 92.3, bottom, blockSize, blockSize);
  level29DeathPlatform1 = new DeathPlatform(centerX, bottom, blockSize * 7.2, blockSize);
  level30DeathPlatform1 = new DeathPlatform(blockSize * 91, bottom, 200, blockSize);
  level31DeathPlatform1 = new DeathPlatform(blockSize * 63.5, bottom, blockSize * 65, blockSize);
  level32DeathPlatform1 = new DeathPlatform(blockSize * 89, bottom, blockSize * 14, blockSize);
  level33DeathPlatform1 = new DeathPlatform(blockSize * 86.5, bottom, blockSize * 19, blockSize);
  level34DeathPlatform1 = new DeathPlatform(blockSize * 59, bottom, blockSize * 74, blockSize);
  level35DeathPlatform1 = new DeathPlatform(blockSize * 93, bottom, blockSize * 6, blockSize);
  level36DeathPlatform1 = new DeathPlatform(blockSize * 65.5, bottom, blockSize * 61, blockSize);
  level37DeathPlatform1 = new DeathPlatform(blockSize * 91, bottom, blockSize * 10, blockSize);
  level38DeathPlatform1 = new DeathPlatform(blockSize * 88.5, bottom, blockSize * 15, blockSize);
  level39DeathPlatform1 = new DeathPlatform(blockSize * 61, bottom, blockSize * 70, blockSize);
  level40DeathPlatform1 = new DeathPlatform(blockSize * 45, blockSize * 50.75, blockSize * 90, halfBlockSize);
  level41DeathPlatform1 = new DeathPlatform(blockSize * 45, blockSize * 50.75, blockSize * 90, halfBlockSize);
  level41DeathPlatform2 = new DeathPlatform(blockSize * 51, blockSize * 47.25, blockSize * 90, halfBlockSize);
  level42DeathPlatform1 = new DeathPlatform(blockSize * 45, blockSize * 50.75, blockSize * 90, halfBlockSize);
  level42DeathPlatform2 = new DeathPlatform(blockSize * 51, blockSize * 47.25, blockSize * 90, halfBlockSize);
  level42DeathPlatform3 = new DeathPlatform(blockSize * 45, blockSize * 43.75, blockSize * 90, halfBlockSize);
  level42DeathPlatform4 = new DeathPlatform(blockSize * 51, blockSize * 40.25, blockSize * 90, halfBlockSize);
  level42DeathPlatform5 = new DeathPlatform(blockSize * 45, blockSize * 36.75, blockSize * 90, halfBlockSize);
  level42DeathPlatform6 = new DeathPlatform(blockSize * 51, blockSize * 33.25, blockSize * 90, halfBlockSize);
  level42DeathPlatform7 = new DeathPlatform(blockSize * 45, blockSize * 29.75, blockSize * 90, halfBlockSize);
  level42DeathPlatform8 = new DeathPlatform(blockSize * 51, blockSize * 26.25, blockSize * 90, halfBlockSize);
  level42DeathPlatform9 = new DeathPlatform(blockSize * 45, blockSize * 22.75, blockSize * 90, halfBlockSize);
  level42DeathPlatform10 = new DeathPlatform(blockSize * 51, blockSize * 19.25, blockSize * 90, halfBlockSize);
  level42DeathPlatform11 = new DeathPlatform(blockSize * 45, blockSize * 15.75, blockSize * 90, halfBlockSize);
  level42DeathPlatform12 = new DeathPlatform(blockSize * 51, blockSize * 12.25, blockSize * 90, halfBlockSize);
  level42DeathPlatform13 = new DeathPlatform(blockSize * 45, blockSize * 8.75, blockSize * 90, halfBlockSize);
  levelClearAreaExample = new LevelClearArea(centerX, blockSize * 30.75, blockSize, blockSize);
  level1ClearArea = new LevelClearArea(right, bottom, blockSize, blockSize);
  level2ClearArea = new LevelClearArea(right, blockSize * 49, blockSize, blockSize);
  level3ClearArea = new LevelClearArea(right, blockSize * 46, blockSize, blockSize);
  level4ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level5ClearArea = new LevelClearArea(right, blockSize * 4, blockSize, blockSize);
  level6ClearArea = new LevelClearArea(right, blockSize * 46, blockSize, blockSize);
  level7ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level8ClearArea = new LevelClearArea(right, blockSize * 4, blockSize, blockSize);
  level9ClearArea = new LevelClearArea(halfBlockSize, blockSize * 46, blockSize, blockSize);
  level10ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level11ClearArea = new LevelClearArea(halfBlockSize, blockSize * 4, blockSize, blockSize);
  level12ClearArea = new LevelClearArea(right, blockSize * 46, blockSize, blockSize);
  level13ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level14ClearArea = new LevelClearArea(right, blockSize * 4, blockSize, blockSize);
  level15ClearArea = new LevelClearArea(right, blockSize * 46, blockSize, blockSize);
  level16ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level17ClearArea = new LevelClearArea(right, blockSize * 4, blockSize, blockSize);
  level18ClearArea = new LevelClearArea(centerX, blockSize * 42.5, blockSize, blockSize);
  level19ClearArea = new LevelClearArea(centerX, blockSize * 4, blockSize, blockSize);
  level20ClearArea = new LevelClearArea(blockSize * 59, blockSize * 42.5, blockSize, blockSize);
  level21ClearArea = new LevelClearArea(blockSize * 59, blockSize * 4, blockSize, blockSize);
  level22ClearArea = new LevelClearArea(centerX, blockSize * 42.5, blockSize, blockSize);
  level23ClearArea = new LevelClearArea(centerX, blockSize * 4, blockSize, blockSize);
  level24ClearArea = new LevelClearArea(blockSize * 58, blockSize * 42.5, blockSize, blockSize);
  level25ClearArea = new LevelClearArea(blockSize * 58, blockSize * 4, blockSize, blockSize);
  level26ClearArea = new LevelClearArea(right, bottom, blockSize, blockSize);
  level27ClearArea = new LevelClearArea(right, bottom, blockSize, blockSize);
  level28ClearArea = new LevelClearArea(right, bottom, blockSize, blockSize);
  level29ClearArea = new LevelClearArea(right, bottom, blockSize, blockSize);
  level30ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level31ClearArea = new LevelClearArea(right, blockSize * 4, blockSize, blockSize);
  level32ClearArea = new LevelClearArea(right, blockSize * 46, blockSize, blockSize);
  level33ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level34ClearArea = new LevelClearArea(right, blockSize * 4, blockSize, blockSize);
  level35ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level36ClearArea = new LevelClearArea(right, blockSize * 4, blockSize, blockSize);
  level37ClearArea = new LevelClearArea(right, blockSize * 46, blockSize, blockSize);
  level38ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level39ClearArea = new LevelClearArea(right, blockSize * 4, blockSize, blockSize);
  level40ClearArea = new LevelClearArea(halfBlockSize, blockSize * 46, blockSize, blockSize);
  level41ClearArea = new LevelClearArea(right, blockSize * 42.5, blockSize, blockSize);
  level42ClearArea = new LevelClearArea(halfBlockSize, blockSize * 4, blockSize, blockSize);
  levelTitles = new ArrayList<>();
  levelDescriptions = new ArrayList<>();
  menuButtons = new ArrayList<>();
  levelsButtons = new ArrayList<>();
  achievementsButtons = new ArrayList<>();
  settingsButtons = new ArrayList<>();
  themeButtons = new ArrayList<>();
  graphicsButtons = new ArrayList<>();
  audioButtons = new ArrayList<>();
  menuSprites = new ArrayList<>();
  levelsSprites = new ArrayList<>();
  achievementsSprites = new ArrayList<>();
  settingsSprites = new ArrayList<>();
  themeSprites = new ArrayList<>();
  graphicsSprites = new ArrayList<>();
  audioSprites = new ArrayList<>();
  tutorial2Sprites = new ArrayList<>();
  tutorial3Sprites = new ArrayList<>();
  tutorial4Sprites = new ArrayList<>();
  tutorial5Sprites = new ArrayList<>();
  level1Sprites = new ArrayList<>();
  level2Sprites = new ArrayList<>();
  level3Sprites = new ArrayList<>();
  level4Sprites = new ArrayList<>();
  level5Sprites = new ArrayList<>();
  level6Sprites = new ArrayList<>();
  level7Sprites = new ArrayList<>();
  level8Sprites = new ArrayList<>();
  level9Sprites = new ArrayList<>();
  level10Sprites = new ArrayList<>();
  level11Sprites = new ArrayList<>();
  level12Sprites = new ArrayList<>();
  level13Sprites = new ArrayList<>();
  level14Sprites = new ArrayList<>();
  level15Sprites = new ArrayList<>();
  level16Sprites = new ArrayList<>();
  level17Sprites = new ArrayList<>();
  level18Sprites = new ArrayList<>();
  level19Sprites = new ArrayList<>();
  level20Sprites = new ArrayList<>();
  level21Sprites = new ArrayList<>();
  level22Sprites = new ArrayList<>();
  level23Sprites = new ArrayList<>();
  level24Sprites = new ArrayList<>();
  level25Sprites = new ArrayList<>();
  level26Sprites = new ArrayList<>();
  level27Sprites = new ArrayList<>();
  level28Sprites = new ArrayList<>();
  level29Sprites = new ArrayList<>();
  level30Sprites = new ArrayList<>();
  level31Sprites = new ArrayList<>();
  level32Sprites = new ArrayList<>();
  level33Sprites = new ArrayList<>();
  level34Sprites = new ArrayList<>();
  level35Sprites = new ArrayList<>();
  level36Sprites = new ArrayList<>();
  level37Sprites = new ArrayList<>();
  level38Sprites = new ArrayList<>();
  level39Sprites = new ArrayList<>();
  level40Sprites = new ArrayList<>();
  level41Sprites = new ArrayList<>();
  level42Sprites = new ArrayList<>();
  levelClears = new ArrayList<>();
  levelDeaths = new ArrayList<>();
  level3Platforms = new ArrayList<>();
  level4Platforms = new ArrayList<>();
  level5Platforms = new ArrayList<>();
  level6Platforms = new ArrayList<>();
  level7Platforms = new ArrayList<>();
  level8Platforms = new ArrayList<>();
  level9Platforms = new ArrayList<>();
  level10Platforms = new ArrayList<>();
  level11Platforms = new ArrayList<>();
  level12Platforms = new ArrayList<>();
  level13Platforms = new ArrayList<>();
  level14Platforms = new ArrayList<>();
  level15Platforms = new ArrayList<>();
  level16Platforms = new ArrayList<>();
  level17Platforms = new ArrayList<>();
  level18Platforms = new ArrayList<>();
  level19Platforms = new ArrayList<>();
  level20Platforms = new ArrayList<>();
  level21Platforms = new ArrayList<>();
  level22Platforms = new ArrayList<>();
  level23Platforms = new ArrayList<>();
  level24Platforms = new ArrayList<>();
  level25Platforms = new ArrayList<>();
  level30Platforms = new ArrayList<>();
  level31Platforms = new ArrayList<>();
  level32Platforms = new ArrayList<>();
  level33Platforms = new ArrayList<>();
  level34Platforms = new ArrayList<>();
  level35Platforms = new ArrayList<>();
  level36Platforms = new ArrayList<>();
  level37Platforms = new ArrayList<>();
  level38Platforms = new ArrayList<>();
  level39Platforms = new ArrayList<>();
  level40Platforms = new ArrayList<>();
  level41Platforms = new ArrayList<>();
  level42Platforms = new ArrayList<>();
  graphicsCheckboxes = new ArrayList<>();
  audioCheckboxes = new ArrayList<>();
  mountains = new ArrayList<Mountain>();
  level26DeathPlatforms = new ArrayList<>();
  level27DeathPlatforms = new ArrayList<>();
  level28DeathPlatforms = new ArrayList<>();
  level29DeathPlatforms = new ArrayList<>();
  level30DeathPlatforms = new ArrayList<>();
  level31DeathPlatforms = new ArrayList<>();
  level32DeathPlatforms = new ArrayList<>();
  level33DeathPlatforms = new ArrayList<>();
  level34DeathPlatforms = new ArrayList<>();
  level35DeathPlatforms = new ArrayList<>();
  level36DeathPlatforms = new ArrayList<>();
  level37DeathPlatforms = new ArrayList<>();
  level38DeathPlatforms = new ArrayList<>();
  level39DeathPlatforms = new ArrayList<>();
  level40DeathPlatforms = new ArrayList<>();
  level41DeathPlatforms = new ArrayList<>();
  level42DeathPlatforms = new ArrayList<>();
  levelTitles.add("One Dimensional");
  levelTitles.add("New Heights");
  levelTitles.add("P In Platformer");
  levelTitles.add("Duality");
  levelTitles.add("Plurality");
  levelTitles.add("Chasm");
  levelTitles.add("Risky Chasm");
  levelTitles.add("Riskier Chasm");
  levelTitles.add("So Close Yet So Far");
  levelTitles.add("Snake");
  levelTitles.add("Long Snake");
  levelTitles.add("B In Blatformer");
  levelTitles.add("Buality");
  levelTitles.add("Bunny Hopping");
  levelTitles.add("Block Chasm");
  levelTitles.add("Blockier Chasm");
  levelTitles.add("Riskiest Chasm");
  levelTitles.add("In And Out");
  levelTitles.add("Ins And Outs");
  levelTitles.add("Creative Level Name");
  levelTitles.add("More Creative Level Name");
  levelTitles.add("Hollow Peaks");
  levelTitles.add("Stairs Without An Offset");
  levelTitles.add("Tilted Knight");
  levelTitles.add("Average Tick Mark");
  levelTitles.add("I Caution Restraint");
  levelTitles.add("The Price To Pay");
  levelTitles.add("Déjà Vu");
  levelTitles.add("Long Jump");
  levelTitles.add("Dangerous Fall");
  levelTitles.add("More Dangerous Fall");
  levelTitles.add("Risky Leap");
  levelTitles.add("Riskier Leap");
  levelTitles.add("Riskiest Leap");
  levelTitles.add("Way More Dangerous Fall");
  levelTitles.add("Even More Dangerous Fall");
  levelTitles.add("Crocodile Pit");
  levelTitles.add("Larger Crocodile Pit");
  levelTitles.add("Largest Crocodile Pit");
  levelTitles.add("Red And Magenta");
  levelTitles.add("Reds And Magentas");
  levelTitles.add("Constricted Path");
  levelDescriptions.add("If you haven't just come from Level 28, welcome. But enough foreshadowing.");
  levelDescriptions.add("I mean, if you haven't gotten the achievement yet, and haven't looked at the tutorial, then...good luck figuring out the jump key.");
  levelDescriptions.add("This is the first level with platforms! But it's expected, not unlike a lot of the things in this game.");
  levelDescriptions.add("If you don't know your average numerical prefixes, why did you even start to play this game?");
  levelDescriptions.add("Surprised I didn't name Level 3 singularity? Well, this isn't a space-themed game, is it?");
  levelDescriptions.add("Well, it isn't a chasm chasm, but I needed a synonym for gap.");
  levelDescriptions.add("Have you figured out the pattern yet? If not, revise MYP Criterion B.");
  levelDescriptions.add("If you have, then you can predict what's coming, like a lot of other levels in the game. Wow, I'm foreshadowing again, aren't I?");
  levelDescriptions.add("A hairpin turn of sorts, except on a differently rotated plane. Guess what the next level is?");
  levelDescriptions.add("You guessed it, double the platforms, double the fun.");
  levelDescriptions.add("At this point, you're probably dreading what comes next. Unless you're a masochist, of course.");
  levelDescriptions.add("Well, I guess 'blockformer' would have been a better name. Oh well.");
  levelDescriptions.add("If you still don't get what 'duality' means, quit already.");
  levelDescriptions.add("I mean, wouldn't you just love this in real life? Well, this brings way to another soon-apparent pattern.");
  levelDescriptions.add("Wow, I wonder who won the award in 'least creative game for SoM'. Certainly not the narrator of this game.");
  levelDescriptions.add("Yes, yes, I know the level titles are getting more and more creative as you progress. Or in Level 28's case, regress.");
  levelDescriptions.add("Well, the trend is broken. But the levels are still pretty much copy-pasted. Wait, lemme Ctrl+C Level 28's code.");
  levelDescriptions.add("Something different! Finally, but it's still just more pain.");
  levelDescriptions.add("Totally didn't just slap the most frequent plural suffix in English twice onto Level 18's name for Level 29's name. I know, I'm quite honest.");
  levelDescriptions.add("At this point, the gameplay has become so repetitive that you can create this level accurate to the pixel without looking at it.");
  levelDescriptions.add("I used another comparitive. Are you surprised?");
  levelDescriptions.add("No, that spelling mistake in Level 21 was deliberate, but I'm not surprised that you haven't noticed.");
  levelDescriptions.add("Surprised I didn't use a superlative for this level? Of course you are, but the reason is that it simply doesn't allow me to copy and paste the level later on.");
  levelDescriptions.add("I know, the proportions aren't to scale. Why not though?");
  levelDescriptions.add("I mean, seriously. Tick marks are longer than sentences at this point. Well, only 3 more levels excluding this one until something grand! If you know addition, look at the number in the top left corner, add 3 to it, and you know what's coming. But you probably knew that anyway.");
  levelDescriptions.add("A whole new mechanic! I know, I know, this is a sight to behold. But the chances are, I haven't spoilt it, as this probably isn't your first attempt...");
  levelDescriptions.add("You probably know about the consequences of this recent mechanic, so here's your useless good luck.");
  levelDescriptions.add("The more-than-once aforementioned Level 28! Well guess what, this is literally the nerfed version. And you still died and/or will die to it again. How pathetic.");
  levelDescriptions.add("You cleared Level 28. I'm surprised, and congratulations to you. However, this level is known as 'the one jump to end it all', so good luck (again).");
  levelDescriptions.add("Wow. I've got to say, I'm impressed. Unless you're the type of person to read this after 42 hours of gameplay on this Processing game. In which case, touch grass.");
  levelDescriptions.add("I mean, you probably know what this level and the next few levels are going to be. Thus, you also probably know that the next few levels are going to be a breeze. Until you mess up.");
  levelDescriptions.add("There's not much to say, other than the large leap necessary can be fatal. But, I mean, after coming this far, that's obvious.");
  levelDescriptions.add("Here's a riskier large leap, and yes, I will keep using modifiers to suggest the difficulty of the level. I really should add a difficulty indicator sometime soon.");
  levelDescriptions.add("The last in this trio! Sadly, Blatformer levels still exist. Well, sad for you. Not for me.");
  levelDescriptions.add("Here's the first of the final 5 Blatformer levels. Then comes sna-. Wait, I thought I said no more foreshadowing.");
  levelDescriptions.add("The last of this duo, without a large leap to end the level. In this case though, falling, even from 100 pixels, is fatal.");
  levelDescriptions.add("Wow, the second last trio. Wait a second, that means there's 42 levels. I guess this game is the meaning of life.");
  levelDescriptions.add("Well, the meaning of life only stands till I update the game with new levels. But we both know that's probably never going to happen.");
  levelDescriptions.add("For the ultimate trio, you could just go onto Google and type 'Sna-'. Well...that would be way too easy and actually fun. Who likes fun? Certainly not you, you're sat (probably) here playing this game.");
  levelDescriptions.add("After you've seen this level, you're going to be depressed as it is a more constrictive trio of levels that 3 you've seen before. You probably don't wanna find out which 3, though.");
  levelDescriptions.add("You've gotten the 'Expert' achievement. Although, the only time you will achieve the title of 'Master' is never, as you're gonna mess up quite soon.");
  levelDescriptions.add("Well, the last level as of typing this message. How sentimental. Just kidding, you're probably super relieved to be staring at Hell's exit that appears for 8.5 seconds, counting the times where it's near invisible for a mortal like you.");
  menuButtons.add(startButton);
  menuButtons.add(exitButton);
  menuButtons.add(tutorialButton);
  menuButtons.add(levelsButton);
  menuButtons.add(achievementsButton);
  menuButtons.add(settingsButton);
  levelsButtons.add(backButton);
  levelsButtons.add(oneButton);
  levelsButtons.add(twoButton);
  levelsButtons.add(threeButton);
  levelsButtons.add(fourButton);
  levelsButtons.add(fiveButton);
  levelsButtons.add(sixButton);
  levelsButtons.add(sevenButton);
  levelsButtons.add(eightButton);
  levelsButtons.add(nineButton);
  levelsButtons.add(tenButton);
  levelsButtons.add(elevenButton);
  levelsButtons.add(twelveButton);
  levelsButtons.add(thirteenButton);
  levelsButtons.add(fourteenButton);
  levelsButtons.add(fifteenButton);
  levelsButtons.add(sixteenButton);
  levelsButtons.add(seventeenButton);
  levelsButtons.add(eighteenButton);
  levelsButtons.add(nineteenButton);
  levelsButtons.add(twentyButton);
  levelsButtons.add(twentyoneButton);
  levelsButtons.add(twentytwoButton);
  levelsButtons.add(twentythreeButton);
  levelsButtons.add(twentyfourButton);
  levelsButtons.add(twentyfiveButton);
  levelsButtons.add(twentysixButton);
  levelsButtons.add(twentysevenButton);
  levelsButtons.add(twentyeightButton);
  levelsButtons.add(twentynineButton);
  levelsButtons.add(thirtyButton);
  levelsButtons.add(thirtyoneButton);
  levelsButtons.add(thirtytwoButton);
  levelsButtons.add(thirtythreeButton);
  levelsButtons.add(thirtyfourButton);
  levelsButtons.add(thirtyfiveButton);
  levelsButtons.add(thirtysixButton);
  levelsButtons.add(thirtysevenButton);
  levelsButtons.add(thirtyeightButton);
  levelsButtons.add(thirtynineButton);
  levelsButtons.add(fortyButton);
  levelsButtons.add(fortyoneButton);
  levelsButtons.add(fortytwoButton);
  achievementsButtons.add(backButton);
  settingsButtons.add(backButton);
  settingsButtons.add(themeButton);
  settingsButtons.add(graphicsButton);
  settingsButtons.add(audioButton);
  settingsButtons.add(aboutButton);
  themeButtons.add(backButton);
  themeButtons.add(cyberpunkButton);
  themeButtons.add(lightButton);
  themeButtons.add(darkButton);
  themeButtons.add(greyscaleButton);
  themeButtons.add(defaultButton);
  themeButtons.add(sunsetButton);
  themeButtons.add(forestButton);
  themeButtons.add(iceButton);
  graphicsButtons.add(backButton);
  audioButtons.add(backButton);
  menuSprites.add(startButton);
  menuSprites.add(exitButton);
  menuSprites.add(tutorialButton);
  menuSprites.add(levelsButton);
  menuSprites.add(achievementsButton);
  menuSprites.add(settingsButton);
  levelsSprites.add(backButton);
  levelsSprites.add(oneButton);
  levelsSprites.add(twoButton);
  levelsSprites.add(threeButton);
  levelsSprites.add(fourButton);
  levelsSprites.add(fiveButton);
  levelsSprites.add(sixButton);
  levelsSprites.add(sevenButton);
  levelsSprites.add(eightButton);
  levelsSprites.add(nineButton);
  levelsSprites.add(tenButton);
  levelsSprites.add(elevenButton);
  levelsSprites.add(twelveButton);
  levelsSprites.add(thirteenButton);
  levelsSprites.add(fourteenButton);
  levelsSprites.add(fifteenButton);
  levelsSprites.add(sixteenButton);
  levelsSprites.add(seventeenButton);
  levelsSprites.add(eighteenButton);
  levelsSprites.add(nineteenButton);
  levelsSprites.add(twentyButton);
  levelsSprites.add(twentyoneButton);
  levelsSprites.add(twentytwoButton);
  levelsSprites.add(twentythreeButton);
  levelsSprites.add(twentyfourButton);
  levelsSprites.add(twentyfiveButton);
  levelsSprites.add(twentysixButton);
  levelsSprites.add(twentysevenButton);
  levelsSprites.add(twentyeightButton);
  levelsSprites.add(twentynineButton);
  levelsSprites.add(thirtyButton);
  levelsSprites.add(thirtyoneButton);
  levelsSprites.add(thirtytwoButton);
  levelsSprites.add(thirtythreeButton);
  levelsSprites.add(thirtyfourButton);
  levelsSprites.add(thirtyfiveButton);
  levelsSprites.add(thirtysixButton);
  levelsSprites.add(thirtysevenButton);
  levelsSprites.add(thirtyeightButton);
  levelsSprites.add(thirtynineButton);
  levelsSprites.add(fortyButton);
  levelsSprites.add(fortyoneButton);
  levelsSprites.add(fortytwoButton);
  achievementsSprites.add(backButton);
  achievementsSprites.add(achievement1);
  achievementsSprites.add(achievement2);
  achievementsSprites.add(achievement3);
  achievementsSprites.add(achievement4);
  achievementsSprites.add(achievement5);
  achievementsSprites.add(achievement6);
  achievementsSprites.add(achievement7);
  achievementsSprites.add(achievement8);
  achievementsSprites.add(achievement9);
  achievementsSprites.add(achievement10);
  achievementsSprites.add(achievement11);
  achievementsSprites.add(achievement12);
  settingsSprites.add(backButton);
  settingsSprites.add(themeButton);
  settingsSprites.add(graphicsButton);
  settingsSprites.add(audioButton);
  settingsSprites.add(aboutButton);
  themeSprites.add(backButton);
  themeSprites.add(cyberpunkButton);
  themeSprites.add(lightButton);
  themeSprites.add(darkButton);
  themeSprites.add(greyscaleButton);
  themeSprites.add(defaultButton);
  themeSprites.add(sunsetButton);
  themeSprites.add(forestButton);
  themeSprites.add(iceButton);
  graphicsSprites.add(backButton);
  graphicsSprites.add(trailCheckbox);
  graphicsSprites.add(jumpAnimationCheckbox);
  audioSprites.add(backButton);
  audioSprites.add(randomClickCheckbox);
  audioSprites.add(buttonClickCheckbox);
  audioSprites.add(levelClearCheckbox);
  audioSprites.add(playerDeathCheckbox);
  tutorial2Sprites.add(player);
  tutorial3Sprites.add(levelClearAreaExample);
  tutorial4Sprites.add(platformExample);
  tutorial5Sprites.add(deathPlatformExample);
  level1Sprites.add(player);
  level1Sprites.add(level1ClearArea);
  level2Sprites.add(player);
  level2Sprites.add(level2ClearArea);
  level3Sprites.add(player);
  level3Sprites.add(level3ClearArea);
  level3Sprites.add(level3Platform1);
  level4Sprites.add(player);
  level4Sprites.add(level4ClearArea);
  level4Sprites.add(level4Platform1);
  level4Sprites.add(level4Platform2);
  level5Sprites.add(player);
  level5Sprites.add(level5ClearArea);
  level5Sprites.add(level5Platform1);
  level5Sprites.add(level5Platform2);
  level5Sprites.add(level5Platform3);
  level5Sprites.add(level5Platform4);
  level5Sprites.add(level5Platform5);
  level5Sprites.add(level5Platform6);
  level5Sprites.add(level5Platform7);
  level5Sprites.add(level5Platform8);
  level5Sprites.add(level5Platform9);
  level5Sprites.add(level5Platform10);
  level5Sprites.add(level5Platform11);
  level5Sprites.add(level5Platform12);
  level5Sprites.add(level5Platform13);
  level6Sprites.add(player);
  level6Sprites.add(level6ClearArea);
  level6Sprites.add(level6Platform1);
  level7Sprites.add(player);
  level7Sprites.add(level7ClearArea);
  level7Sprites.add(level7Platform1);
  level7Sprites.add(level7Platform2);
  level8Sprites.add(player);
  level8Sprites.add(level8ClearArea);
  level8Sprites.add(level8Platform1);
  level8Sprites.add(level8Platform2);
  level8Sprites.add(level8Platform3);
  level8Sprites.add(level8Platform4);
  level8Sprites.add(level8Platform5);
  level8Sprites.add(level8Platform6);
  level8Sprites.add(level8Platform7);
  level8Sprites.add(level8Platform8);
  level8Sprites.add(level8Platform9);
  level8Sprites.add(level8Platform10);
  level8Sprites.add(level8Platform11);
  level8Sprites.add(level8Platform12);
  level8Sprites.add(level8Platform13);
  level9Sprites.add(player);
  level9Sprites.add(level9ClearArea);
  level9Sprites.add(level9Platform1);
  level10Sprites.add(player);
  level10Sprites.add(level10ClearArea);
  level10Sprites.add(level10Platform1);
  level10Sprites.add(level10Platform2);
  level11Sprites.add(player);
  level11Sprites.add(level11ClearArea);
  level11Sprites.add(level11Platform1);
  level11Sprites.add(level11Platform2);
  level11Sprites.add(level11Platform3);
  level11Sprites.add(level11Platform4);
  level11Sprites.add(level11Platform5);
  level11Sprites.add(level11Platform6);
  level11Sprites.add(level11Platform7);
  level11Sprites.add(level11Platform8);
  level11Sprites.add(level11Platform9);
  level11Sprites.add(level11Platform10);
  level11Sprites.add(level11Platform11);
  level11Sprites.add(level11Platform12);
  level11Sprites.add(level11Platform13);
  level12Sprites.add(player);
  level12Sprites.add(level12ClearArea);
  level12Sprites.add(level12Platform1);
  level13Sprites.add(player);
  level13Sprites.add(level13ClearArea);
  level13Sprites.add(level13Platform1);
  level13Sprites.add(level13Platform2);
  level14Sprites.add(player);
  level14Sprites.add(level14ClearArea);
  level14Sprites.add(level14Platform1);
  level14Sprites.add(level14Platform2);
  level14Sprites.add(level14Platform3);
  level14Sprites.add(level14Platform4);
  level14Sprites.add(level14Platform5);
  level14Sprites.add(level14Platform6);
  level14Sprites.add(level14Platform7);
  level14Sprites.add(level14Platform8);
  level14Sprites.add(level14Platform9);
  level14Sprites.add(level14Platform10);
  level14Sprites.add(level14Platform11);
  level14Sprites.add(level14Platform12);
  level14Sprites.add(level14Platform13);
  level15Sprites.add(player);
  level15Sprites.add(level15ClearArea);
  level15Sprites.add(level15Platform1);
  level16Sprites.add(player);
  level16Sprites.add(level16ClearArea);
  level16Sprites.add(level16Platform1);
  level16Sprites.add(level16Platform2);
  level17Sprites.add(player);
  level17Sprites.add(level17ClearArea);
  level17Sprites.add(level17Platform1);
  level17Sprites.add(level17Platform2);
  level17Sprites.add(level17Platform3);
  level17Sprites.add(level17Platform4);
  level17Sprites.add(level17Platform5);
  level17Sprites.add(level17Platform6);
  level17Sprites.add(level17Platform7);
  level17Sprites.add(level17Platform8);
  level17Sprites.add(level17Platform9);
  level17Sprites.add(level17Platform10);
  level17Sprites.add(level17Platform11);
  level17Sprites.add(level17Platform12);
  level17Sprites.add(level17Platform13);
  level18Sprites.add(player);
  level18Sprites.add(level18ClearArea);
  level18Sprites.add(level18Platform1);
  level18Sprites.add(level18Platform2);
  level19Sprites.add(player);
  level19Sprites.add(level19ClearArea);
  level19Sprites.add(level19Platform1);
  level19Sprites.add(level19Platform2);
  level19Sprites.add(level19Platform3);
  level19Sprites.add(level19Platform4);
  level19Sprites.add(level19Platform5);
  level19Sprites.add(level19Platform6);
  level19Sprites.add(level19Platform7);
  level19Sprites.add(level19Platform8);
  level19Sprites.add(level19Platform9);
  level19Sprites.add(level19Platform10);
  level19Sprites.add(level19Platform11);
  level19Sprites.add(level19Platform12);
  level19Sprites.add(level19Platform13);
  level20Sprites.add(player);
  level20Sprites.add(level20ClearArea);
  level20Sprites.add(level20Platform1);
  level20Sprites.add(level20Platform2);
  level21Sprites.add(player);
  level21Sprites.add(level21ClearArea);
  level21Sprites.add(level21Platform1);
  level21Sprites.add(level21Platform2);
  level21Sprites.add(level21Platform3);
  level21Sprites.add(level21Platform4);
  level21Sprites.add(level21Platform5);
  level21Sprites.add(level21Platform6);
  level21Sprites.add(level21Platform7);
  level21Sprites.add(level21Platform8);
  level21Sprites.add(level21Platform9);
  level21Sprites.add(level21Platform10);
  level21Sprites.add(level21Platform11);
  level21Sprites.add(level21Platform12);
  level21Sprites.add(level21Platform13);
  level22Sprites.add(player);
  level22Sprites.add(level22ClearArea);
  level22Sprites.add(level22Platform1);
  level22Sprites.add(level22Platform2);
  level23Sprites.add(player);
  level23Sprites.add(level23ClearArea);
  level23Sprites.add(level23Platform1);
  level23Sprites.add(level23Platform2);
  level23Sprites.add(level23Platform3);
  level23Sprites.add(level23Platform4);
  level23Sprites.add(level23Platform5);
  level23Sprites.add(level23Platform6);
  level23Sprites.add(level23Platform7);
  level23Sprites.add(level23Platform8);
  level23Sprites.add(level23Platform9);
  level23Sprites.add(level23Platform10);
  level23Sprites.add(level23Platform11);
  level23Sprites.add(level23Platform12);
  level23Sprites.add(level23Platform13);
  level24Sprites.add(player);
  level24Sprites.add(level24ClearArea);
  level24Sprites.add(level24Platform1);
  level24Sprites.add(level24Platform2);
  level25Sprites.add(player);
  level25Sprites.add(level25ClearArea);
  level25Sprites.add(level25Platform1);
  level25Sprites.add(level25Platform2);
  level25Sprites.add(level25Platform3);
  level25Sprites.add(level25Platform4);
  level25Sprites.add(level25Platform5);
  level25Sprites.add(level25Platform6);
  level25Sprites.add(level25Platform7);
  level25Sprites.add(level25Platform8);
  level25Sprites.add(level25Platform9);
  level25Sprites.add(level25Platform10);
  level25Sprites.add(level25Platform11);
  level25Sprites.add(level25Platform12);
  level25Sprites.add(level25Platform13);
  level26Sprites.add(player);
  level26Sprites.add(level26ClearArea);
  level26Sprites.add(level26DeathPlatform1);
  level27Sprites.add(player);
  level27Sprites.add(level27ClearArea);
  level27Sprites.add(level27DeathPlatform1);
  level27Sprites.add(level27DeathPlatform2);
  level28Sprites.add(player);
  level28Sprites.add(level28ClearArea);
  level28Sprites.add(level28DeathPlatform1);
  level28Sprites.add(level28DeathPlatform2);
  level28Sprites.add(level28DeathPlatform3);
  level28Sprites.add(level28DeathPlatform4);
  level28Sprites.add(level28DeathPlatform5);
  level28Sprites.add(level28DeathPlatform6);
  level28Sprites.add(level28DeathPlatform7);
  level28Sprites.add(level28DeathPlatform8);
  level28Sprites.add(level28DeathPlatform9);
  level28Sprites.add(level28DeathPlatform10);
  level28Sprites.add(level28DeathPlatform11);
  level28Sprites.add(level28DeathPlatform12);
  level28Sprites.add(level28DeathPlatform13);
  level28Sprites.add(level28DeathPlatform14);
  level28Sprites.add(level28DeathPlatform15);
  level28Sprites.add(level28DeathPlatform16);
  level28Sprites.add(level28DeathPlatform17);
  level28Sprites.add(level28DeathPlatform18);
  level28Sprites.add(level28DeathPlatform19);
  level28Sprites.add(level28DeathPlatform20);
  level28Sprites.add(level28DeathPlatform21);
  level28Sprites.add(level28DeathPlatform22);
  level28Sprites.add(level28DeathPlatform23);
  level28Sprites.add(level28DeathPlatform24);
  level28Sprites.add(level28DeathPlatform25);
  level28Sprites.add(level28DeathPlatform26);
  level28Sprites.add(level28DeathPlatform27);
  level28Sprites.add(level28DeathPlatform28);
  level28Sprites.add(level28DeathPlatform29);
  level29Sprites.add(player);
  level29Sprites.add(level29ClearArea);
  level29Sprites.add(level29DeathPlatform1);
  level30Sprites.add(player);
  level30Sprites.add(level30ClearArea);
  level30Sprites.add(level30Platform1);
  level30Sprites.add(level30Platform2);
  level30Sprites.add(level30DeathPlatform1);
  level31Sprites.add(player);
  level31Sprites.add(level31ClearArea);
  level31Sprites.add(level31Platform1);
  level31Sprites.add(level31Platform2);
  level31Sprites.add(level31Platform3);
  level31Sprites.add(level31Platform4);
  level31Sprites.add(level31Platform5);
  level31Sprites.add(level31Platform6);
  level31Sprites.add(level31Platform7);
  level31Sprites.add(level31Platform8);
  level31Sprites.add(level31Platform9);
  level31Sprites.add(level31Platform10);
  level31Sprites.add(level31Platform11);
  level31Sprites.add(level31Platform12);
  level31Sprites.add(level31Platform13);
  level31Sprites.add(level31DeathPlatform1);
  level32Sprites.add(player);
  level32Sprites.add(level32ClearArea);
  level32Sprites.add(level32Platform1);
  level32Sprites.add(level32DeathPlatform1);
  level33Sprites.add(player);
  level33Sprites.add(level33ClearArea);
  level33Sprites.add(level33Platform1);
  level33Sprites.add(level33Platform2);
  level33Sprites.add(level33DeathPlatform1);
  level34Sprites.add(player);
  level34Sprites.add(level34ClearArea);
  level34Sprites.add(level34Platform1);
  level34Sprites.add(level34Platform2);
  level34Sprites.add(level34Platform3);
  level34Sprites.add(level34Platform4);
  level34Sprites.add(level34Platform5);
  level34Sprites.add(level34Platform6);
  level34Sprites.add(level34Platform7);
  level34Sprites.add(level34Platform8);
  level34Sprites.add(level34Platform9);
  level34Sprites.add(level34Platform10);
  level34Sprites.add(level34Platform11);
  level34Sprites.add(level34Platform12);
  level34Sprites.add(level34Platform13);
  level34Sprites.add(level34DeathPlatform1);
  level35Sprites.add(player);
  level35Sprites.add(level35ClearArea);
  level35Sprites.add(level35Platform1);
  level35Sprites.add(level35Platform2);
  level35Sprites.add(level35DeathPlatform1);
  level36Sprites.add(player);
  level36Sprites.add(level36ClearArea);
  level36Sprites.add(level36Platform1);
  level36Sprites.add(level36Platform2);
  level36Sprites.add(level36Platform3);
  level36Sprites.add(level36Platform4);
  level36Sprites.add(level36Platform5);
  level36Sprites.add(level36Platform6);
  level36Sprites.add(level36Platform7);
  level36Sprites.add(level36Platform8);
  level36Sprites.add(level36Platform9);
  level36Sprites.add(level36Platform10);
  level36Sprites.add(level36Platform11);
  level36Sprites.add(level36Platform12);
  level36Sprites.add(level36Platform13);
  level36Sprites.add(level36DeathPlatform1);
  level37Sprites.add(player);
  level37Sprites.add(level37ClearArea);
  level37Sprites.add(level37Platform1);
  level37Sprites.add(level37DeathPlatform1);
  level38Sprites.add(player);
  level38Sprites.add(level38ClearArea);
  level38Sprites.add(level38Platform1);
  level38Sprites.add(level38Platform2);
  level38Sprites.add(level38DeathPlatform1);
  level39Sprites.add(player);
  level39Sprites.add(level39ClearArea);
  level39Sprites.add(level39Platform1);
  level39Sprites.add(level39Platform2);
  level39Sprites.add(level39Platform3);
  level39Sprites.add(level39Platform4);
  level39Sprites.add(level39Platform5);
  level39Sprites.add(level39Platform6);
  level39Sprites.add(level39Platform7);
  level39Sprites.add(level39Platform8);
  level39Sprites.add(level39Platform9);
  level39Sprites.add(level39Platform10);
  level39Sprites.add(level39Platform11);
  level39Sprites.add(level39Platform12);
  level39Sprites.add(level39Platform13);
  level39Sprites.add(level39DeathPlatform1);
  level40Sprites.add(player);
  level40Sprites.add(level40ClearArea);
  level40Sprites.add(level40Platform1);
  level40Sprites.add(level40DeathPlatform1);
  level41Sprites.add(player);
  level41Sprites.add(level41ClearArea);
  level41Sprites.add(level41Platform1);
  level41Sprites.add(level41Platform2);
  level41Sprites.add(level41DeathPlatform1);
  level41Sprites.add(level41DeathPlatform2);
  level42Sprites.add(player);
  level42Sprites.add(level42ClearArea);
  level42Sprites.add(level42Platform1);
  level42Sprites.add(level42Platform2);
  level42Sprites.add(level42Platform3);
  level42Sprites.add(level42Platform4);
  level42Sprites.add(level42Platform5);
  level42Sprites.add(level42Platform6);
  level42Sprites.add(level42Platform7);
  level42Sprites.add(level42Platform8);
  level42Sprites.add(level42Platform9);
  level42Sprites.add(level42Platform10);
  level42Sprites.add(level42Platform11);
  level42Sprites.add(level42Platform12);
  level42Sprites.add(level42Platform13);
  level42Sprites.add(level42DeathPlatform1);
  level42Sprites.add(level42DeathPlatform2);
  level42Sprites.add(level42DeathPlatform3);
  level42Sprites.add(level42DeathPlatform4);
  level42Sprites.add(level42DeathPlatform5);
  level42Sprites.add(level42DeathPlatform6);
  level42Sprites.add(level42DeathPlatform7);
  level42Sprites.add(level42DeathPlatform8);
  level42Sprites.add(level42DeathPlatform9);
  level42Sprites.add(level42DeathPlatform10);
  level42Sprites.add(level42DeathPlatform11);
  level42Sprites.add(level42DeathPlatform12);
  level42Sprites.add(level42DeathPlatform13);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelClears.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  levelDeaths.add(false);
  level3Platforms.add(level3Platform1);
  level4Platforms.add(level4Platform1);
  level4Platforms.add(level4Platform2);
  level5Platforms.add(level5Platform1);
  level5Platforms.add(level5Platform2);
  level5Platforms.add(level5Platform3);
  level5Platforms.add(level5Platform4);
  level5Platforms.add(level5Platform5);
  level5Platforms.add(level5Platform6);
  level5Platforms.add(level5Platform7);
  level5Platforms.add(level5Platform8);
  level5Platforms.add(level5Platform9);
  level5Platforms.add(level5Platform10);
  level5Platforms.add(level5Platform11);
  level5Platforms.add(level5Platform12);
  level5Platforms.add(level5Platform13);
  level6Platforms.add(level6Platform1);
  level7Platforms.add(level7Platform1);
  level7Platforms.add(level7Platform2);
  level8Platforms.add(level8Platform1);
  level8Platforms.add(level8Platform2);
  level8Platforms.add(level8Platform3);
  level8Platforms.add(level8Platform4);
  level8Platforms.add(level8Platform5);
  level8Platforms.add(level8Platform6);
  level8Platforms.add(level8Platform7);
  level8Platforms.add(level8Platform8);
  level8Platforms.add(level8Platform9);
  level8Platforms.add(level8Platform10);
  level8Platforms.add(level8Platform11);
  level8Platforms.add(level8Platform12);
  level8Platforms.add(level8Platform13);
  level9Platforms.add(level9Platform1);
  level10Platforms.add(level10Platform1);
  level10Platforms.add(level10Platform2);
  level11Platforms.add(level11Platform1);
  level11Platforms.add(level11Platform2);
  level11Platforms.add(level11Platform3);
  level11Platforms.add(level11Platform4);
  level11Platforms.add(level11Platform5);
  level11Platforms.add(level11Platform6);
  level11Platforms.add(level11Platform7);
  level11Platforms.add(level11Platform8);
  level11Platforms.add(level11Platform9);
  level11Platforms.add(level11Platform10);
  level11Platforms.add(level11Platform11);
  level11Platforms.add(level11Platform12);
  level11Platforms.add(level11Platform13);
  level12Platforms.add(level12Platform1);
  level13Platforms.add(level13Platform1);
  level13Platforms.add(level13Platform2);
  level14Platforms.add(level14Platform1);
  level14Platforms.add(level14Platform2);
  level14Platforms.add(level14Platform3);
  level14Platforms.add(level14Platform4);
  level14Platforms.add(level14Platform5);
  level14Platforms.add(level14Platform6);
  level14Platforms.add(level14Platform7);
  level14Platforms.add(level14Platform8);
  level14Platforms.add(level14Platform9);
  level14Platforms.add(level14Platform10);
  level14Platforms.add(level14Platform11);
  level14Platforms.add(level14Platform12);
  level14Platforms.add(level14Platform13);
  level15Platforms.add(level15Platform1);
  level16Platforms.add(level16Platform1);
  level16Platforms.add(level16Platform2);
  level17Platforms.add(level17Platform1);
  level17Platforms.add(level17Platform2);
  level17Platforms.add(level17Platform3);
  level17Platforms.add(level17Platform4);
  level17Platforms.add(level17Platform5);
  level17Platforms.add(level17Platform6);
  level17Platforms.add(level17Platform7);
  level17Platforms.add(level17Platform8);
  level17Platforms.add(level17Platform9);
  level17Platforms.add(level17Platform10);
  level17Platforms.add(level17Platform11);
  level17Platforms.add(level17Platform12);
  level17Platforms.add(level17Platform13);
  level18Platforms.add(level18Platform1);
  level18Platforms.add(level18Platform2);
  level19Platforms.add(level19Platform1);
  level19Platforms.add(level19Platform2);
  level19Platforms.add(level19Platform3);
  level19Platforms.add(level19Platform4);
  level19Platforms.add(level19Platform5);
  level19Platforms.add(level19Platform6);
  level19Platforms.add(level19Platform7);
  level19Platforms.add(level19Platform8);
  level19Platforms.add(level19Platform9);
  level19Platforms.add(level19Platform10);
  level19Platforms.add(level19Platform11);
  level19Platforms.add(level19Platform12);
  level19Platforms.add(level19Platform13);
  level20Platforms.add(level20Platform1);
  level20Platforms.add(level20Platform2);
  level21Platforms.add(level21Platform1);
  level21Platforms.add(level21Platform2);
  level21Platforms.add(level21Platform3);
  level21Platforms.add(level21Platform4);
  level21Platforms.add(level21Platform5);
  level21Platforms.add(level21Platform6);
  level21Platforms.add(level21Platform7);
  level21Platforms.add(level21Platform8);
  level21Platforms.add(level21Platform9);
  level21Platforms.add(level21Platform10);
  level21Platforms.add(level21Platform11);
  level21Platforms.add(level21Platform12);
  level21Platforms.add(level21Platform13);
  level22Platforms.add(level22Platform1);
  level22Platforms.add(level22Platform2);
  level23Platforms.add(level23Platform1);
  level23Platforms.add(level23Platform2);
  level23Platforms.add(level23Platform3);
  level23Platforms.add(level23Platform4);
  level23Platforms.add(level23Platform5);
  level23Platforms.add(level23Platform6);
  level23Platforms.add(level23Platform7);
  level23Platforms.add(level23Platform8);
  level23Platforms.add(level23Platform9);
  level23Platforms.add(level23Platform10);
  level23Platforms.add(level23Platform11);
  level23Platforms.add(level23Platform12);
  level23Platforms.add(level23Platform13);
  level24Platforms.add(level24Platform1);
  level24Platforms.add(level24Platform2);
  level25Platforms.add(level25Platform1);
  level25Platforms.add(level25Platform2);
  level25Platforms.add(level25Platform3);
  level25Platforms.add(level25Platform4);
  level25Platforms.add(level25Platform5);
  level25Platforms.add(level25Platform6);
  level25Platforms.add(level25Platform7);
  level25Platforms.add(level25Platform8);
  level25Platforms.add(level25Platform9);
  level25Platforms.add(level25Platform10);
  level25Platforms.add(level25Platform11);
  level25Platforms.add(level25Platform12);
  level25Platforms.add(level25Platform13);
  level30Platforms.add(level30Platform1);
  level30Platforms.add(level30Platform2);
  level31Platforms.add(level31Platform1);
  level31Platforms.add(level31Platform2);
  level31Platforms.add(level31Platform3);
  level31Platforms.add(level31Platform4);
  level31Platforms.add(level31Platform5);
  level31Platforms.add(level31Platform6);
  level31Platforms.add(level31Platform7);
  level31Platforms.add(level31Platform8);
  level31Platforms.add(level31Platform9);
  level31Platforms.add(level31Platform10);
  level31Platforms.add(level31Platform11);
  level31Platforms.add(level31Platform12);
  level31Platforms.add(level31Platform13);
  level32Platforms.add(level32Platform1);
  level33Platforms.add(level33Platform1);
  level33Platforms.add(level33Platform2);
  level34Platforms.add(level34Platform1);
  level34Platforms.add(level34Platform2);
  level34Platforms.add(level34Platform3);
  level34Platforms.add(level34Platform4);
  level34Platforms.add(level34Platform5);
  level34Platforms.add(level34Platform6);
  level34Platforms.add(level34Platform7);
  level34Platforms.add(level34Platform8);
  level34Platforms.add(level34Platform9);
  level34Platforms.add(level34Platform10);
  level34Platforms.add(level34Platform11);
  level34Platforms.add(level34Platform12);
  level34Platforms.add(level34Platform13);
  level35Platforms.add(level35Platform1);
  level35Platforms.add(level35Platform2);
  level36Platforms.add(level36Platform1);
  level36Platforms.add(level36Platform2);
  level36Platforms.add(level36Platform3);
  level36Platforms.add(level36Platform4);
  level36Platforms.add(level36Platform5);
  level36Platforms.add(level36Platform6);
  level36Platforms.add(level36Platform7);
  level36Platforms.add(level36Platform8);
  level36Platforms.add(level36Platform9);
  level36Platforms.add(level36Platform10);
  level36Platforms.add(level36Platform11);
  level36Platforms.add(level36Platform12);
  level36Platforms.add(level36Platform13);
  level37Platforms.add(level37Platform1);
  level38Platforms.add(level38Platform1);
  level38Platforms.add(level38Platform2);
  level39Platforms.add(level39Platform1);
  level39Platforms.add(level39Platform2);
  level39Platforms.add(level39Platform3);
  level39Platforms.add(level39Platform4);
  level39Platforms.add(level39Platform5);
  level39Platforms.add(level39Platform6);
  level39Platforms.add(level39Platform7);
  level39Platforms.add(level39Platform8);
  level39Platforms.add(level39Platform9);
  level39Platforms.add(level39Platform10);
  level39Platforms.add(level39Platform11);
  level39Platforms.add(level39Platform12);
  level39Platforms.add(level39Platform13);
  level40Platforms.add(level40Platform1);
  level41Platforms.add(level41Platform1);
  level41Platforms.add(level41Platform2);
  level42Platforms.add(level42Platform1);
  level42Platforms.add(level42Platform2);
  level42Platforms.add(level42Platform3);
  level42Platforms.add(level42Platform4);
  level42Platforms.add(level42Platform5);
  level42Platforms.add(level42Platform6);
  level42Platforms.add(level42Platform7);
  level42Platforms.add(level42Platform8);
  level42Platforms.add(level42Platform9);
  level42Platforms.add(level42Platform10);
  level42Platforms.add(level42Platform11);
  level42Platforms.add(level42Platform12);
  level42Platforms.add(level42Platform13);
  graphicsCheckboxes.add(trailCheckbox);
  graphicsCheckboxes.add(jumpAnimationCheckbox);
  audioCheckboxes.add(randomClickCheckbox);
  audioCheckboxes.add(buttonClickCheckbox);
  audioCheckboxes.add(levelClearCheckbox);
  audioCheckboxes.add(playerDeathCheckbox);
  mountains.add(mountain1);
  mountains.add(mountain2);
  mountains.add(mountain3);
  mountains.add(mountain4);
  level26DeathPlatforms.add(level26DeathPlatform1);
  level27DeathPlatforms.add(level27DeathPlatform1);
  level27DeathPlatforms.add(level27DeathPlatform2);
  level28DeathPlatforms.add(level28DeathPlatform1);
  level28DeathPlatforms.add(level28DeathPlatform1);
  level28DeathPlatforms.add(level28DeathPlatform2);
  level28DeathPlatforms.add(level28DeathPlatform3);
  level28DeathPlatforms.add(level28DeathPlatform4);
  level28DeathPlatforms.add(level28DeathPlatform5);
  level28DeathPlatforms.add(level28DeathPlatform6);
  level28DeathPlatforms.add(level28DeathPlatform7);
  level28DeathPlatforms.add(level28DeathPlatform8);
  level28DeathPlatforms.add(level28DeathPlatform9);
  level28DeathPlatforms.add(level28DeathPlatform10);
  level28DeathPlatforms.add(level28DeathPlatform11);
  level28DeathPlatforms.add(level28DeathPlatform12);
  level28DeathPlatforms.add(level28DeathPlatform13);
  level28DeathPlatforms.add(level28DeathPlatform14);
  level28DeathPlatforms.add(level28DeathPlatform15);
  level28DeathPlatforms.add(level28DeathPlatform16);
  level28DeathPlatforms.add(level28DeathPlatform17);
  level28DeathPlatforms.add(level28DeathPlatform18);
  level28DeathPlatforms.add(level28DeathPlatform19);
  level28DeathPlatforms.add(level28DeathPlatform20);
  level28DeathPlatforms.add(level28DeathPlatform21);
  level28DeathPlatforms.add(level28DeathPlatform22);
  level28DeathPlatforms.add(level28DeathPlatform23);
  level28DeathPlatforms.add(level28DeathPlatform24);
  level28DeathPlatforms.add(level28DeathPlatform25);
  level28DeathPlatforms.add(level28DeathPlatform26);
  level28DeathPlatforms.add(level28DeathPlatform27);
  level28DeathPlatforms.add(level28DeathPlatform28);
  level28DeathPlatforms.add(level28DeathPlatform29);
  level29DeathPlatforms.add(level29DeathPlatform1);
  level30DeathPlatforms.add(level30DeathPlatform1);
  level31DeathPlatforms.add(level31DeathPlatform1);
  level32DeathPlatforms.add(level32DeathPlatform1);
  level33DeathPlatforms.add(level33DeathPlatform1);
  level34DeathPlatforms.add(level34DeathPlatform1);
  level35DeathPlatforms.add(level35DeathPlatform1);
  level36DeathPlatforms.add(level36DeathPlatform1);
  level37DeathPlatforms.add(level37DeathPlatform1);
  level38DeathPlatforms.add(level38DeathPlatform1);
  level39DeathPlatforms.add(level39DeathPlatform1);
  level40DeathPlatforms.add(level40DeathPlatform1);
  level41DeathPlatforms.add(level41DeathPlatform1);
  level41DeathPlatforms.add(level41DeathPlatform2);
  level42DeathPlatforms.add(level42DeathPlatform1);
  level42DeathPlatforms.add(level42DeathPlatform2);
  level42DeathPlatforms.add(level42DeathPlatform3);
  level42DeathPlatforms.add(level42DeathPlatform4);
  level42DeathPlatforms.add(level42DeathPlatform5);
  level42DeathPlatforms.add(level42DeathPlatform6);
  level42DeathPlatforms.add(level42DeathPlatform7);
  level42DeathPlatforms.add(level42DeathPlatform8);
  level42DeathPlatforms.add(level42DeathPlatform9);
  level42DeathPlatforms.add(level42DeathPlatform10);
  level42DeathPlatforms.add(level42DeathPlatform11);
  level42DeathPlatforms.add(level42DeathPlatform12);
  level42DeathPlatforms.add(level42DeathPlatform13);
  for (int row = 0; row < 5; row++) {
    for (int col = 0; col < 8; col++) {
      sections[row][col] = loadImage(getParentPath(1) + "data/images/sections/" + theme + File.separator + theme + "Section[" + row + "][" + col + "].png");
    }
  }
  setColours(true);
  backdrop();
  fullScreen();
  textAlign(CENTER);
  rectMode(CENTER);
  ellipseMode(CENTER);
  imageMode(CENTER);
  strokeWeight(blockSize * 0.15);
  noStroke();
  noCursor();
}
